// ==================== COMPLETE LEAGUES DATA ====================
// ONLY data declarations - NO functions or thresholds here

const leaguesData = {

"MLS Eastern Conference": {
    id: "mls-east",
    logo: "mls/mlslogo.jpg",
    isBasketball: false,
    teams: [
        { team: "Philadelphia", MP: 34, MW: 20, MD: 6, GF: 57, GA: 35, logo: "mls/philadelphialogo.png" },
        { team: "Cincinnati", MP: 34, MW: 20, MD: 5, GF: 52, GA: 40, logo: "mls/cincinnatlogo.png" },
        { team: "Inter Miami", MP: 34, MW: 19, MD: 8, GF: 81, GA: 55, logo: "mls/intermiamilogo.png" },
        { team: "Charlotte", MP: 34, MW: 19, MD: 2, GF: 55, GA: 46, logo: "mls/charlottelogo.png" },
        { team: "New York", MP: 34, MW: 17, MD: 5, GF: 50, GA: 44, logo: "mls/newyorklogo.png" },
        { team: "Nashville", MP: 34, MW: 16, MD: 6, GF: 58, GA: 45, logo: "mls/nashvillelogo.png" },
        { team: "Columbus", MP: 34, MW: 14, MD: 12, GF: 55, GA: 41, logo: "mls/columbuslogo.png" },
        { team: "Chicago", MP: 34, MW: 15, MD: 8, GF: 68, GA: 60, logo: "mls/chicagologo.png" },
        { team: "Orlando", MP: 34, MW: 14, MD: 11, GF: 63, GA: 51, logo: "mls/orlandologo.png" },
        { team: "NY Red Bulls", MP: 34, MW: 12, MD: 7, GF: 48, GA: 47, logo: "mls/nyredbullslogo.png" },
        { team: "New England", MP: 34, MW: 9, MD: 9, GF: 44, GA: 51, logo: "mls/newenglandlogo.png" },
        { team: "Toronto", MP: 34, MW: 6, MD: 14, GF: 37, GA: 44, logo: "mls/torontologo.png" },
        { team: "Montreal", MP: 34, MW: 6, MD: 10, GF: 34, GA: 60, logo: "mls/monteallogo.png" },
        { team: "Atlanta", MP: 34, MW: 5, MD: 13, GF: 38, GA: 63, logo: "mls/atlantalogo.png" }
    ],
    fixtures: [
        { home: "Montreal", away: "Toronto", date: "2026-07-17" },
        { home: "Chicago", away: "Vancouver", date: "2026-07-17" },
        { home: "Seattle", away: "Portland", date: "2026-07-17" },
        { home: "Nashville", away: "Atlanta", date: "2026-07-18" },
        { home: "LA Galaxy", away: "LAFC", date: "2026-07-18" },
        { home: "Cincinnati", away: "Vancouver", date: "2026-07-23" },
        { home: "Columbus", away: "New York City", date: "2026-07-23" },
        { home: "Inter Miami", away: "Chicago", date: "2026-07-23" },
        { home: "Philadelphia", away: "NY Red Bulls", date: "2026-07-23" },
        { home: "New England", away: "Toronto", date: "2026-07-23" },
        { home: "Charlotte", away: "Atlanta", date: "2026-07-23" },
		{ home: "Austin", away: "Seattle", date: "2026-07-23" },
		{ home: "Houston", away: "DC United", date: "2026-07-23" },
		{ home: "Nashville", away: "Montreal", date: "2026-07-23" },
		{ home: "Sporting KC", away: "Minnesota", date: "2026-07-23" },
		{ home: "Colorado", away: "San Diego", date: "2026-07-23" }
    ]
},

"MLS Western Conference": {
    id: "mls-west",
    logo: "mls/mlslogo.jpg",
    isBasketball: false,
    teams: [
        { team: "DC United", MP: 34, MW: 5, MD: 11, GF: 30, GA: 66, logo: "mls/dcunitedlogo.png" },
        { team: "San Diego", MP: 34, MW: 19, MD: 6, GF: 64, GA: 41, logo: "mls/sandiegologo.jpg" },
        { team: "Vancouver", MP: 34, MW: 18, MD: 9, GF: 66, GA: 38, logo: "mls/vancouverlogo.png" },
        { team: "LAFC", MP: 34, MW: 17, MD: 9, GF: 65, GA: 40, logo: "mls/lafclogo.png" },
        { team: "Minnesota", MP: 34, MW: 16, MD: 10, GF: 56, GA: 39, logo: "mls/minnesotslogo.png" },
        { team: "Seattle", MP: 34, MW: 15, MD: 10, GF: 58, GA: 48, logo: "mls/seattlelogo.png" },
        { team: "Austin", MP: 34, MW: 13, MD: 8, GF: 37, GA: 45, logo: "mls/austinlogo.png" },
        { team: "Dallas", MP: 34, MW: 11, MD: 11, GF: 52, GA: 55, logo: "mls/dallaslogo.png" },
        { team: "Portland", MP: 34, MW: 11, MD: 11, GF: 41, GA: 48, logo: "mls/portlandlogo.png" },
        { team: "Real Salt Lake", MP: 34, MW: 12, MD: 5, GF: 38, GA: 49, logo: "mls/realsaltlakelogo.png" },
        { team: "San Jose", MP: 34, MW: 11, MD: 8, GF: 60, GA: 63, logo: "mls/sanjoselogo.png" },
        { team: "Colorado", MP: 34, MW: 11, MD: 8, GF: 40, GA: 56, logo: "mls/coloradologo.png" },
        { team: "Houston Dynamo", MP: 34, MW: 9, MD: 10, GF: 43, GA: 56, logo: "mls/houstondynamologo.png" },
        { team: "St. Louis", MP: 34, MW: 8, MD: 8, GF: 44, GA: 58, logo: "mls/stlouislogo.png" },
        { team: "LA Galaxy", MP: 34, MW: 7, MD: 9, GF: 46, GA: 66, logo: "mls/lagalaxylogo.png" },
        { team: "Sporting KC", MP: 34, MW: 7, MD: 7, GF: 46, GA: 70, logo: "mls/sportingkclogo.png" }
    ],
    fixtures: [
        { home: "LA Galaxy", away: "St. Louis", date: "2026-07-23" },
        { home: "LAFC", away: "Real Salt Lake", date: "2026-07-23" },
        { home: "Portland", away: "Dallas", date: "2026-07-23" },
        { home: "Eatrhquakes", away: "Orlando", date: "2026-07-23" },
        { home: "Atlanta", away: "Montreal", date: "2026-06-15" },
        { home: "NY Red Bulls", away: "Dallas", date: "2026-06-15" },
        { home: "Columbus", away: "Minnesota", date: "2026-06-15" }
    ]
},
/*
"Argentine Liga Profesional - Group A": {
    id: "argentina-group-a",
    logo: "argentina/argentinaprimeralogo.png",
    isBasketball: false,
    teams: [
        { team: "Estudiantes", MP: 16, MW: 9, MD: 4, GF: 19, GA: 7, logo: "argentina/estudianteslogo.png" },
        { team: "Boca", MP: 16, MW: 8, MD: 6, GF: 22, GA: 9, logo: "argentina/bocalogo.png" },
        { team: "Vélez Sársfield", MP: 16, MW: 7, MD: 7, GF: 18, GA: 12, logo: "argentina/velezlogo.png" },
        { team: "Talleres", MP: 16, MW: 7, MD: 5, GF: 17, GA: 13, logo: "argentina/estudianteslogo.png" },
        { team: "Independiente", MP: 16, MW: 6, MD: 6, GF: 24, GA: 20, logo: "argentina/tellereslogo.png" },
        { team: "Lanús", MP: 16, MW: 6, MD: 6, GF: 18, GA: 15, logo: "argentina/lanuslogo.png" },
        { team: "San Lorenzo", MP: 16, MW: 5, MD: 7, GF: 14, GA: 14, logo: "argentina/sanlorenzologo.png" },
        { team: "Unión", MP: 16, MW: 5, MD: 6, GF: 24, GA: 20, logo: "argentina/unionlogo.png" },
        { team: "Instituto", MP: 16, MW: 6, MD: 3, GF: 17, GA: 17, logo: "argentina/institutologo.png" },
        { team: "Defensa", MP: 16, MW: 4, MD: 7, GF: 18, GA: 21, logo: "argentina/defensalogo.png" },
        { team: "Gimnasia Esgirma", MP: 16, MW: 5, MD: 4, GF: 14, GA: 22, logo: "argentina/gimnasiaesgrimalogo.png" },
        { team: "Platense", MP: 16, MW: 3, MD: 7, GF: 10, GA: 15, logo: "argentina/platesnselogo.png" },
        { team: "Central Córdoba", MP: 16, MW: 4, MD: 4, GF: 11, GA: 21, logo: "argentina/centralcordobalogo.png" },
        { team: "Newell's", MP: 16, MW: 3, MD: 6, GF: 15, GA: 27, logo: "argentina/newellslogo.png" },
        { team: "Deportivo Riestra", MP: 16, MW: 1, MD: 8, GF: 5, GA: 12, logo: "argentina/riestralogo.jpg" }
    ],
    fixtures: [
        { home: "Barracas Central", away: "Banfield", date: "2026-06-15" },
        { home: "Lanus", away: "Riestra", date: "2026-06-15" },
        { home: "Central Cordoba", away: "Boca Juniors", date: "2026-06-15" },
        { home: "Union", away: "Telleres", date: "2026-06-15" },
        { home: "San Lorenzo", away: "Independiente", date: "2026-06-15" },
        { home: "Platense", away: "Estudiantes", date: "2026-06-15" },
        { home: "Aldosivi", away: "Independiente Rivadavia", date: "2026-06-15" },
        { home: "Central", away: "Tigre", date: "2026-06-15" },
        { home: "Gimnasia LP", away: "Argentinos Juniors", date: "2026-06-15" },
        { home: "Racing Club", away: "Huracan", date: "2026-06-15" },
        { home: "Belgrano", away: "Sarmiento", date: "2026-06-15" },
        { home: "River Plate", away: "Atletico Tucuman", date: "2026-06-15" },
        { home: "Gimnasia Esgrima", away: "Defensa", date: "2026-06-15" },
        { home: "Velez Sarsfield", away: "Newells", date: "2026-06-15" },
        { home: "Estudiantes De Rio Cuarto", away: "Instituto", date: "2026-06-15" }
    ]
},
*/
"Argentine Primera B Metropolitana": {
    id: "argentina-primera-b",
    logo: "argentina/primera-b.png",
    isBasketball: false,
    teams: [
        { team: "Midland", MP: 20, MW: 11, MD: 7, ML: 2, GF: 24, GA: 5, logo: "argentina/midland.png" },
        { team: "Real Pilar", MP: 20, MW: 10, MD: 6, ML: 4, GF: 27, GA: 16, logo: "argentina/realpilar.png" },
        { team: "Argentino de Merlo", MP: 20, MW: 10, MD: 5, ML: 5, GF: 25, GA: 15, logo: "argentina/argentinomerlo.png" },
        { team: "Acassuso", MP: 20, MW: 9, MD: 7, ML: 4, GF: 25, GA: 18, logo: "argentina/acassuso.png" },
        { team: "Excursionistas", MP: 20, MW: 9, MD: 5, ML: 6, GF: 21, GA: 16, logo: "argentina/excursionistas.png" },
        { team: "Dock Sud", MP: 20, MW: 8, MD: 7, ML: 5, GF: 29, GA: 25, logo: "argentina/docksud.png" },
        { team: "Villa San Carlos", MP: 20, MW: 9, MD: 3, ML: 8, GF: 24, GA: 28, logo: "argentina/villasantacarlos.png" },
        { team: "Brown (A)", MP: 20, MW: 7, MD: 7, ML: 6, GF: 18, GA: 17, logo: "argentina/brown.png" },
        { team: "Deportivo Merlo", MP: 20, MW: 7, MD: 7, ML: 6, GF: 16, GA: 17, logo: "argentina/deportivomerlo.png" },
        { team: "Liniers", MP: 20, MW: 8, MD: 3, ML: 9, GF: 27, GA: 22, logo: "argentina/liniers.png" },
        { team: "UAI Urquiza", MP: 20, MW: 5, MD: 11, ML: 4, GF: 16, GA: 18, logo: "argentina/uaiurquiza.png" },
        { team: "Comunicaciones", MP: 20, MW: 7, MD: 4, ML: 9, GF: 19, GA: 18, logo: "argentina/comunicaciones.png" },
        { team: "Laferrere", MP: 20, MW: 5, MD: 9, ML: 6, GF: 21, GA: 20, logo: "argentina/laferrere.png" },
        { team: "Argentino Quilmes", MP: 20, MW: 5, MD: 9, ML: 6, GF: 21, GA: 24, logo: "argentina/argentoquilmes.png" },
        { team: "San Martín Burzaco", MP: 20, MW: 6, MD: 6, ML: 8, GF: 19, GA: 25, logo: "argentina/sanmartinburzaco.png" },
        { team: "Dep. Armenio", MP: 20, MW: 5, MD: 8, ML: 7, GF: 17, GA: 19, logo: "argentina/deparmenio.png" },
        { team: "Dálmine", MP: 20, MW: 5, MD: 8, ML: 7, GF: 20, GA: 27, logo: "argentina/dalmine.png" },
        { team: "Flandria", MP: 20, MW: 5, MD: 7, ML: 8, GF: 12, GA: 18, logo: "argentina/flandria.png" },
        { team: "Sportivo Italiano", MP: 20, MW: 4, MD: 9, ML: 7, GF: 15, GA: 16, logo: "argentina/sportivoitaliano.png" },
        { team: "Sacachispas", MP: 20, MW: 2, MD: 9, ML: 9, GF: 13, GA: 24, logo: "argentina/sacachispas.png" },
        { team: "Fenix Pilar", MP: 20, MW: 1, MD: 7, ML: 12, GF: 8, GA: 29, logo: "argentina/fenixpilar.png" }
    ],
    fixtures: [
        { home: "Deportivo Merlo", away: "Laferrere", date: "TBD" },
        { home: "Brown (A)", away: "Comunicaciones", date: "2026-06-05" },
        { home: "Dálmine", away: "Villa San Carlos", date: "2026-06-06" },
		{ home: "Flandria", away: "Argentino Quilmes", date: "2026-06-06" },
		{ home: "Dep. Armenio", away: "Defensores Unidos", date: "2026-06-06" },
		{ home: "Excursionistas", away: "San Martín Burzaco", date: "2026-06-06" },
		{ home: "Argentino de Merlo", away: "Deportivo Camioneros", date: "2026-06-06" },
		{ home: "Laferrere", away: "Dock Stud", date: "2026-06-07" },
        { home: "UAI Urquiza", away: "liniers", date: "2026-06-08" },
        //{ home: "Flandria", away: "Argentino Quilmes", date: "2026-06-15" },
        //{ home: "Dep. Armenio", away: "Deportivo Camioneros", date: "2026-06-15" },
        //{ home: "Ituzaingó", away: "Real Pilar", date: "2026-06-15" }
    ]
},
/*
"Argentine Liga Profesional - Group B": {
    id: "argentina-group-b",
    logo: "argentina/argentinaprimeralogo.png",
    isBasketball: false,
    teams: [
        { team: "Independiente Rivadavia", MP: 16, MW: 10, MD: 4, GF: 29, GA: 15, logo: "argentina/rivadavialogo.png" },
        { team: "River Plate", MP: 16, MW: 9, MD: 2, GF: 22, GA: 12, logo: "argentina/riverplatelogo.png" },
        { team: "Argentinos Juniors", MP: 16, MW: 8, MD: 5, GF: 17, GA: 13, logo: "argentina/argentinoslogo.png" },
        { team: "Central", MP: 16, MW: 8, MD: 4, GF: 20, GA: 16, logo: "argentina/centrallogo.png" },
        { team: "Belgrano", MP: 16, MW: 7, MD: 5, GF: 17, GA: 13, logo: "argentina/belgranologo.png" },
        { team: "Gimnasia LP", MP: 16, MW: 8, MD: 2, GF: 19, GA: 19, logo: "argentina/gimnasialplogo.png" },
        { team: "Huracán", MP: 16, MW: 5, MD: 7, GF: 17, GA: 13, logo: "argentina/huracanlogo.png" },
        { team: "Racing Club", MP: 16, MW: 5, MD: 6, GF: 17, GA: 15, logo: "argentina/racingclublogo.png" },
        { team: "Barracas Central", MP: 16, MW: 5, MD: 6, GF: 15, GA: 15, logo: "argentina/barracascentrallogo.png" },
        { team: "Tigre", MP: 16, MW: 4, MD: 8, GF: 18, GA: 15, logo: "argentina/tigrelogo.png" },
        { team: "Sarmiento", MP: 16, MW: 6, MD: 1, GF: 13, GA: 20, logo: "argentina/sarmientologo.png" },
        { team: "Banfield", MP: 16, MW: 5, MD: 3, GF: 17, GA: 19, logo: "argentina/banfieldlogo.png" },
        { team: "Atlético Tucumán", MP: 16, MW: 3, MD: 5, GF: 15, GA: 20, logo: "argentina/atleticotucumanlogo.png" },
        { team: "Aldosivi", MP: 16, MW: 0, MD: 8, GF: 6, GA: 19, logo: "argentina/aldosivilogo.png" },
        { team: "Estudiantes de Río Cuarto", MP: 16, MW: 1, MD: 2, GF: 5, GA: 24, logo: "argentina/estudiantesdelriocuartologo.png" }
    ],
    fixtures: [
        { home: "Independiente Rivadavia", away: "River Plate", date: "2026-06-15" },
        { home: "Argentinos Juniors", away: "Central", date: "2026-06-15" },
        { home: "Belgrano", away: "Gimnasia LP", date: "2026-06-15" },
        { home: "Huracán", away: "Racing Club", date: "2026-06-15" },
        { home: "Barracas Central", away: "Tigre", date: "2026-06-15" },
        { home: "Sarmiento", away: "Banfield", date: "2026-06-15" },
        { home: "Atlético Tucumán", away: "Aldosivi", date: "2026-06-15" },
        { home: "Estudiantes de Río Cuarto", away: "Independiente Rivadavia", date: "2026-06-15" },
        { home: "River Plate", away: "Argentinos Juniors", date: "2026-06-15" },
        { home: "Central", away: "Belgrano", date: "2026-06-15" },
        { home: "Gimnasia LP", away: "Huracán", date: "2026-06-15" },
        { home: "Racing Club", away: "Barracas Central", date: "2026-06-15" },
        { home: "Tigre", away: "Sarmiento", date: "2026-06-15" },
        { home: "Banfield", away: "Atlético Tucumán", date: "2026-06-15" },
        { home: "Aldosivi", away: "Estudiantes de Río Cuarto", date: "2026-06-15" }
    ]
},
*/


"Argentine Reserve League - Group A": {
    id: "arg-reserve-a",
    logo: "argentina/reserve.png",
    isBasketball: false,
    teams: [
        { team: "Velez Sarsfield 2", MP: 15, MW: 11, MD: 2, ML: 2, GF: 33, GA: 11, logo: "argentina/velez2.png" },
        { team: "Racing Club 2", MP: 15, MW: 7, MD: 6, ML: 2, GF: 23, GA: 16, logo: "argentina/racing2.png" },
        { team: "River Plate 2", MP: 16, MW: 7, MD: 4, ML: 5, GF: 21, GA: 16, logo: "argentina/river2.png" },
        { team: "Argentinos Jrs 2", MP: 15, MW: 6, MD: 6, ML: 3, GF: 18, GA: 13, logo: "argentina/argentinos2.png" },
        { team: "Atl. Tucuman 2", MP: 15, MW: 7, MD: 3, ML: 5, GF: 21, GA: 22, logo: "argentina/tucuman2.png" },
        { team: "Rosario Central 2", MP: 15, MW: 6, MD: 5, ML: 4, GF: 21, GA: 16, logo: "argentina/rosario2.png" },
        { team: "Instituto 2", MP: 15, MW: 5, MD: 8, ML: 2, GF: 18, GA: 14, logo: "argentina/instituto2.png" },
        { team: "Talleres Cordoba 2", MP: 15, MW: 6, MD: 4, ML: 5, GF: 21, GA: 15, logo: "argentina/talleres2.png" },
        { team: "Gimnasia L.P. 2", MP: 15, MW: 6, MD: 4, ML: 5, GF: 18, GA: 13, logo: "argentina/gimnasia2.png" },
        { team: "San Lorenzo 2", MP: 15, MW: 6, MD: 4, ML: 5, GF: 18, GA: 19, logo: "argentina/sanlorenzo2.png" },
        { team: "Union de Santa Fe 2", MP: 15, MW: 4, MD: 8, ML: 3, GF: 18, GA: 19, logo: "argentina/union2.png" },
        { team: "Banfield 2", MP: 16, MW: 5, MD: 5, ML: 6, GF: 12, GA: 16, logo: "argentina/banfield2.png" },
        { team: "Gimnasia Mendoza 2", MP: 15, MW: 5, MD: 4, ML: 6, GF: 14, GA: 17, logo: "argentina/gimnasiamza2.png" },
        { team: "Barracas Central 2", MP: 15, MW: 4, MD: 4, ML: 7, GF: 10, GA: 19, logo: "argentina/barracas2.png" },
        { team: "Tigre 2", MP: 16, MW: 4, MD: 3, ML: 9, GF: 13, GA: 21, logo: "argentina/tigre2.png" },
        { team: "Sarmiento Junin 2", MP: 16, MW: 4, MD: 3, ML: 9, GF: 15, GA: 24, logo: "argentina/sarmiento2.png" },
        { team: "Godoy Cruz 2", MP: 15, MW: 3, MD: 2, ML: 10, GF: 16, GA: 27, logo: "argentina/godoy2.png" },
        { team: "Aldosivi 2", MP: 15, MW: 3, MD: 2, ML: 10, GF: 12, GA: 26, logo: "argentina/aldosivi2.png" }
    ],
    fixtures: [
        { home: "Estudiantes L.P. 2", away: "Ind. Rivadavia 2", date: "2026-06-03" },
        { home: "Gimnasia Mendoza 2", away: "Gimnasia L.P. 2", date: "2026-06-03" },
        { home: "Instituto 2", away: "Atl. Tucuman 2", date: "2026-06-03" },
        { home: "Rosario Central 2", away: "Racing Club 2", date: "2026-06-03" },
        { home: "San Lorenzo 2", away: "Velez Sarsfield 2", date: "2026-06-04" },
        { home: "Talleres Cordoba 2", away: "Argentinos Jrs 2", date: "2026-06-05" },
        { home: "Union de Santa Fe 2", away: "Atl. Tucuman 2", date: "2026-06-09" },
        { home: "Racing Club 2", away: "Banfield 2", date: "2026-06-09" },
        { home: "Argentinos Jrs 2", away: "Barracas Central 2", date: "2026-06-10" },
        { home: "San Lorenzo 2", away: "Instituto 2", date: "2026-06-10" },
        { home: "Sarmiento Junin 2", away: "Talleres Cordoba 2", date: "2026-06-10" },
        { home: "Velez Sarsfield 2", away: "Tigre 2", date: "2026-06-10" }
    ]
},

"Argentine Reserve League - Group B": {
    id: "arg-reserve-b",
    logo: "argentina/reserve.png",
    isBasketball: false,
    teams: [
        { team: "Boca Juniors 2", MP: 15, MW: 10, MD: 3, ML: 2, GF: 27, GA: 7, logo: "argentina/boca2.png" },
        { team: "Independiente 2", MP: 16, MW: 9, MD: 3, ML: 4, GF: 29, GA: 14, logo: "argentina/independiente2.png" },
        { team: "Newells Old Boys 2", MP: 16, MW: 9, MD: 3, ML: 4, GF: 21, GA: 13, logo: "argentina/newells2.png" },
        { team: "Quilmes 2", MP: 16, MW: 9, MD: 3, ML: 4, GF: 14, GA: 9, logo: "argentina/quilmes2.png" },
        { team: "Lanus 2", MP: 15, MW: 9, MD: 2, ML: 4, GF: 31, GA: 19, logo: "argentina/lanus2.png" },
        { team: "Defensa y Justicia 2", MP: 15, MW: 8, MD: 4, ML: 3, GF: 35, GA: 17, logo: "argentina/defensa2.png" },
        { team: "Huracan 2", MP: 16, MW: 7, MD: 4, ML: 5, GF: 22, GA: 15, logo: "argentina/huracan2.png" },
        { team: "Platense 2", MP: 15, MW: 6, MD: 5, ML: 4, GF: 15, GA: 16, logo: "argentina/platense2.png" },
        { team: "Belgrano 2", MP: 15, MW: 7, MD: 2, ML: 6, GF: 22, GA: 25, logo: "argentina/belgrano2.png" },
        { team: "Estudiantes L.P. 2", MP: 15, MW: 6, MD: 4, ML: 5, GF: 18, GA: 13, logo: "argentina/estudiantes2.png" },
        { team: "Deportivo Riestra 2", MP: 16, MW: 6, MD: 3, ML: 7, GF: 24, GA: 18, logo: "argentina/riestra2.png" },
        { team: "Ferro 2", MP: 16, MW: 6, MD: 3, ML: 7, GF: 17, GA: 19, logo: "argentina/ferro2.png" },
        { team: "Ind. Rivadavia 2", MP: 15, MW: 5, MD: 3, ML: 7, GF: 19, GA: 21, logo: "argentina/rivadavia2.png" },
        { team: "Colon Santa Fe 2", MP: 16, MW: 4, MD: 3, ML: 9, GF: 14, GA: 21, logo: "argentina/colon2.png" },
        { team: "Central Cordoba 2", MP: 15, MW: 3, MD: 4, ML: 8, GF: 14, GA: 29, logo: "argentina/centralcordoba2.png" },
        { team: "Atl. Rafaela 2", MP: 15, MW: 3, MD: 1, ML: 11, GF: 19, GA: 28, logo: "argentina/rafaela2.png" },
        { team: "Estudiantes Rio Cuarto 2", MP: 16, MW: 1, MD: 5, ML: 10, GF: 8, GA: 31, logo: "argentina/estudiantesrc2.png" },
        { team: "San Martin S.J. 2", MP: 15, MW: 2, MD: 2, ML: 11, GF: 14, GA: 46, logo: "argentina/sanmartin2.png" }
    ],
    fixtures: [
        { home: "Boca Juniors 2", away: "Defensa y Justicia 2", date: "2026-06-04" },
        { home: "Atl. Rafaela 2", away: "Lanus 2", date: "2026-06-04" },
        { home: "Barracas Central 2", away: "Aldosivi 2", date: "2026-06-04" },
        { home: "Platense 2", away: "Belgrano 2", date: "2026-06-04" },
        { home: "Central Cordoba 2", away: "San Martin S.J. 2", date: "2026-06-05" },
        { home: "Defensa y Justicia 2", away: "Ferro 2", date: "2026-06-08" },
        { home: "Ind. Rivadavia 2", away: "Quilmes 2", date: "2026-06-08" },
        { home: "Belgrano 2", away: "Atl. Rafaela 2", date: "2026-06-09" },
        { home: "Deportivo Riestra 2", away: "Platense 2", date: "2026-06-09" },
        { home: "Lanus 2", away: "Independiente 2", date: "2026-06-09" },
        { home: "Central Cordoba 2", away: "Colon Santa Fe 2", date: "2026-06-10" },
        { home: "Newells Old Boys 2", away: "Boca Juniors 2", date: "2026-06-10" },
        { home: "Estudiantes Rio Cuarto 2", away: "Huracan 2", date: "2026-06-10" }
    ]
},
"Japanese J1 League": {
    id: "j1-league",
    logo: "japan/j1logo.png",
    isBasketball: false,
    teams: [
        { team: "Kashima Antlers", MP: 38, MW: 23, MD: 7, GF: 58, GA: 31, logo: "japan/kashimaantlerslogo.png" },
        { team: "Kashiwa", MP: 38, MW: 21, MD: 12, GF: 60, GA: 34, logo: "japan/kashiwalogo.png" },
        { team: "Kyoto", MP: 38, MW: 19, MD: 11, GF: 62, GA: 40, logo: "japan/kyotologo.png" },
        { team: "Sanfrecce", MP: 38, MW: 20, MD: 8, GF: 46, GA: 28, logo: "japan/sanfreecelogo.png" },
        { team: "Vissel Kobe", MP: 38, MW: 18, MD: 10, GF: 46, GA: 33, logo: "japan/visselkobelogo.png" },
        { team: "Machida", MP: 38, MW: 17, MD: 9, GF: 52, GA: 38, logo: "japan/machidalogo.png" },
        { team: "Urawa Reds", MP: 38, MW: 16, MD: 11, GF: 45, GA: 39, logo: "japan/urawaredslogo.png" },
        { team: "Kawasaki", MP: 38, MW: 15, MD: 12, GF: 67, GA: 57, logo: "japan/kawasakilogo.png" },
        { team: "Gamba Osaka", MP: 38, MW: 17, MD: 6, GF: 53, GA: 55, logo: "japan/gambaosakalogo.png" },
        { team: "Cerezo Osaka", MP: 38, MW: 14, MD: 10, GF: 60, GA: 57, logo: "japan/cerezoosakalogo.png" },
        { team: "FC Tokyo", MP: 38, MW: 13, MD: 11, GF: 41, GA: 48, logo: "japan/fctokyologo.png" },
        { team: "Avispa", MP: 38, MW: 12, MD: 12, GF: 34, GA: 38, logo: "japan/avispalogo.png" },
        { team: "Okayama", MP: 38, MW: 12, MD: 9, GF: 34, GA: 43, logo: "japan/okayamalogo.png" },
        { team: "Shimizu", MP: 38, MW: 11, MD: 11, GF: 41, GA: 51, logo: "japan/shimizulogo.png" },
        { team: "Yokohama FM", MP: 38, MW: 12, MD: 7, GF: 46, GA: 47, logo: "japan/yokohamafmlogo.png" },
        { team: "Nagoya", MP: 38, MW: 11, MD: 10, GF: 44, GA: 56, logo: "japan/nagoyalogo.png" },
        { team: "Tokyo Verdy", MP: 38, MW: 11, MD: 10, GF: 23, GA: 41, logo: "japan/nagoyalogo.png" },
        { team: "Yokohama FC", MP: 38, MW: 9, MD: 8, GF: 27, GA: 45, logo: "japan/yokogamafclogo.png" },
        { team: "Shonan", MP: 38, MW: 8, MD: 8, GF: 36, GA: 63, logo: "japan/shonanlogo.png" },
        { team: "Niigata", MP: 38, MW: 4, MD: 12, GF: 36, GA: 67, logo: "japan/niigatalogologo.png" }
    ],
    fixtures: [
        { home: "Kashima Antlers", away: "Vissel Kobe", date: "2026-06-06" },
        { home: "Machida", away: "Nagoya", date: "2026-06-06" },
        { home: "Tokyo Verdy", away: "Gamba Osaka", date: "2026-06-06" },
        { home: "Urawa Reds", away: "Okayama", date: "2026-06-06" },
		{ home: "Yokohama FM", away: "Shimizu", date: "2026-06-06" },
		{ home: "Kashiwa", away: "Kyoto", date: "2026-06-06" },
		{ home: "Kawasaki", away: "Sanfrecce", date: "2026-06-06" },
    ]
},

"Japanese J2 League": {
    id: "j2-league",
    logo: "japan/j2logo.png",
    isBasketball: false,
    teams: [
        { team: "Mito HollyHock", MP: 38, MW: 20, MD: 10, GF: 55, GA: 34, logo: "japan/mitologo.png" },
        { team: "V-Varen Nagasaki", MP: 38, MW: 19, MD: 13, GF: 63, GA: 44, logo: "japan/nagasaki.png" },
        { team: "JEF United", MP: 38, MW: 20, MD: 9, GF: 56, GA: 34, logo: "japan/jeflogo.png" },
        { team: "Tokushima Vortis", MP: 38, MW: 18, MD: 11, GF: 45, GA: 24, logo: "japan/tokushimavortislogo.png" },
        { team: "Júbilo Iwata", MP: 38, MW: 19, MD: 7, GF: 59, GA: 51, logo: "japan/jubiloiwatalogo.png" },
        { team: "Omiya Ardija", MP: 38, MW: 18, MD: 9, GF: 60, GA: 39, logo: "japan/omiyalogo.png" },
        { team: "Vegalta Sendai", MP: 38, MW: 16, MD: 14, GF: 47, GA: 36, logo: "japan/velgatalogo.png" },
        { team: "Sagan Tosu", MP: 38, MW: 16, MD: 10, GF: 46, GA: 43, logo: "japan/sagantosulogo.png" },
        { team: "Iwaki FC", MP: 38, MW: 15, MD: 11, GF: 55, GA: 44, logo: "japan/iwakilogo.png" },
        { team: "Montedio Yamagata", MP: 38, MW: 15, MD: 8, GF: 58, GA: 54, logo: "japan/yamagatalogo.png" },
        { team: "Imabari", MP: 38, MW: 13, MD: 14, GF: 46, GA: 46, logo: "japan/imabarilogo.png" },
        { team: "Consadole Sapporo", MP: 38, MW: 16, MD: 5, GF: 50, GA: 63, logo: "japan/consadolelogo.png" },
        { team: "Ventforet Kofu", MP: 38, MW: 11, MD: 11, GF: 37, GA: 45, logo: "japan/ventforetlogo.png" },
        { team: "Blaublitz", MP: 38, MW: 11, MD: 10, GF: 43, GA: 59, logo: "japan/blaublitzlogo.png" },
        { team: "Fujieda MYFC", MP: 38, MW: 9, MD: 12, GF: 41, GA: 50, logo: "japan/fujieda.png" },
        { team: "Oita Trinita", MP: 38, MW: 8, MD: 14, GF: 27, GA: 44, logo: "japan/oitalogo.png" },
        { team: "Kataller Toyama", MP: 38, MW: 9, MD: 10, GF: 34, GA: 49, logo: "japan/toyamalogo.png" },
        { team: "Roasso Kumamoto", MP: 38, MW: 9, MD: 10, GF: 41, GA: 57, logo: "japan/roassologo.png" },
        { team: "Renofa Yamaguchi", MP: 38, MW: 7, MD: 15, GF: 36, GA: 47, logo: "japan/renofalogo.png" },
        { team: "Ehime FC", MP: 38, MW: 3, MD: 13, GF: 35, GA: 71, logo: "japan/ehimelogo.png" }
    ],
    fixtures: [
        { home: "Kamatamare Sanuki", away: "Nagano", date: "2026-06-05" },
        { home: "Niigata", away: "Consadole Sapporo", date: "2026-06-06" },
        { home: "Omiya Ardija", away: "Kochi United", date: "2026-06-06" },
        { home: "Tochigi City FC", away: "Reilac Shiga", date: "2026-06-06" },
        { home: "Sagamihara", away: "Roasso Kumamoto", date: "2026-06-06" },
        { home: "Matsumoto Yamaga", away: "Nara Club", date: "2026-06-06" },
        { home: "Yokohama FC", away: "Renofa Yamaguchi", date: "2026-06-06" },
        { home: "Fujieda MYFC", away: "Ehime FC", date: "2026-06-06" },
        { home: "FC Gifu", away: "Tottori", date: "2026-06-07" },
        { home: "Júbilo Iwata", away: "Osaka", date: "2026-06-07" },
        { home: "Sagan Tosu", away: "Shonan Bellmare", date: "2026-06-07" },
        { home: "Vanraure Hachinohe", away: "Imabari", date: "2026-06-07" },
        { home: "Tokushima Vortis", away: "Iwaki FC", date: "2026-06-07" },
        { home: "Blaublitz", away: "Kagoshima United", date: "2026-06-07" },
        { home: "Vegalta Sendai", away: "Kataller Toyama", date: "2026-06-06" },
        { home: "Tegevajaro Miyazaki", away: "Ventforet Kofu", date: "2026-06-06" },
        //{ home: "Montedio Yamagata", away: "Shonan Bellmare", date: "2026-06-15" },
        //{ home: "Tottori", away: "Oita Trinita", date: "2026-06-15" },
        //{ home: "Blaublitz Tochigi FC", away: "Kanazawa", date: "2026-06-15" },
        //{ home: "Ehime FC", away: "Mito HollyHock", date: "2026-06-15" }
    ]
},

"Chilean Primera División": {
    id: "chile",
    logo: "chile/chile.png",
    isBasketball: false,
    teams: [
        { rank: 1, team: "Coquimbo", MP: 30, MW: 23, MD: 6, ML: 1, GF: 49, GA: 17, logo: "chile/coquimbo.png" },
        { rank: 2, team: "Universidad Católica", MP: 30, MW: 17, MD: 7, ML: 6, GF: 44, GA: 26, logo: "chile/ucatolica.png" },
        { rank: 3, team: "O'Higgins", MP: 30, MW: 16, MD: 8, ML: 6, GF: 43, GA: 34, logo: "chile/ohiggins.png" },
        { rank: 4, team: "Universidad de Chile", MP: 30, MW: 17, MD: 4, ML: 9, GF: 58, GA: 32, logo: "chile/uchile.png" },
        { rank: 5, team: "Audax Italiano", MP: 30, MW: 16, MD: 4, ML: 10, GF: 51, GA: 43, logo: "chile/audax.png" },
        { rank: 6, team: "Palestino", MP: 30, MW: 14, MD: 7, ML: 9, GF: 42, GA: 31, logo: "chile/palestino.png" },
        { rank: 7, team: "Cobresal", MP: 30, MW: 14, MD: 5, ML: 11, GF: 38, GA: 38, logo: "chile/cobresal.png" },
        { rank: 8, team: "Colo-Colo", MP: 30, MW: 12, MD: 8, ML: 10, GF: 46, GA: 36, logo: "chile/colocolo.png" },
        { rank: 9, team: "Huachipato", MP: 30, MW: 12, MD: 7, ML: 11, GF: 43, GA: 42, logo: "chile/huachipato.png" },
        { rank: 10, team: "Ñublense", MP: 30, MW: 8, MD: 9, ML: 13, GF: 31, GA: 40, logo: "chile/nublense.png" },
        { rank: 11, team: "Deportes Limache", MP: 30, MW: 8, MD: 7, ML: 15, GF: 36, GA: 43, logo: "chile/limache.png" },
        { rank: 12, team: "Unión La Calera", MP: 30, MW: 8, MD: 5, ML: 17, GF: 28, GA: 39, logo: "chile/unionlacalera.png" },
        { rank: 13, team: "La Serena", MP: 30, MW: 7, MD: 6, ML: 17, GF: 32, GA: 52, logo: "chile/laserena.png" },
        { rank: 14, team: "Everton", MP: 30, MW: 6, MD: 8, ML: 16, GF: 27, GA: 44, logo: "chile/everton.png" },
        { rank: 15, team: "Deportes Iquique", MP: 30, MW: 6, MD: 6, ML: 18, GF: 34, GA: 60, logo: "chile/iquique.png" },
        { rank: 16, team: "Unión Española", MP: 30, MW: 6, MD: 3, ML: 21, GF: 33, GA: 58, logo: "chile/unespanola.png" }
    ],
    fixtures: [
        { home: "Deportes Limache", away: "Coquimbo", date: "2026-06-15" },
        { home: "O'Higgins", away: "Everton", date: "2026-06-15" },
        { home: "Palestino", away: "Audax Italiano", date: "2026-06-15" }
    ]
},

"Chinese Super League": {
    id: "csl",
    logo: "china/csl.png",
    isBasketball: false,
    teams: [
        { team: "Shanghai Port", MP: 30, MW: 20, MD: 6, ML: 4, GF: 72, GA: 44, logo: "china/shanghaiport.png" },
        { team: "Shanghai Shenhua", MP: 30, MW: 19, MD: 7, ML: 4, GF: 67, GA: 35, logo: "china/shanghaishenhua.png" },
        { team: "Chengdu Rongcheng", MP: 30, MW: 17, MD: 9, ML: 4, GF: 60, GA: 28, logo: "china/chengdu.png" },
        { team: "Beijing Guoan", MP: 30, MW: 17, MD: 6, ML: 7, GF: 69, GA: 46, logo: "china/beijing.png" },
        { team: "Shandong Taishan", MP: 30, MW: 15, MD: 8, ML: 7, GF: 69, GA: 46, logo: "china/shandong.png" },
        { team: "Tianjin Jinmen Tiger", MP: 30, MW: 12, MD: 8, ML: 10, GF: 40, GA: 41, logo: "china/tianjin.png" },
        { team: "Zhejiang", MP: 30, MW: 10, MD: 12, ML: 8, GF: 60, GA: 51, logo: "china/zhejiang.png" },
        { team: "Yunnan Yukun", MP: 30, MW: 11, MD: 9, ML: 10, GF: 47, GA: 52, logo: "china/yunnan.png" },
        { team: "Qingdao Youth Island", MP: 30, MW: 10, MD: 10, ML: 10, GF: 39, GA: 43, logo: "china/qingdao.png" },
        { team: "Henan", MP: 30, MW: 10, MD: 7, ML: 13, GF: 52, GA: 48, logo: "china/henan.png" },
        { team: "Dalian Yingbo", MP: 30, MW: 9, MD: 9, ML: 12, GF: 30, GA: 45, logo: "china/dalian.png" },
        { team: "Shenzhen Peng City", MP: 30, MW: 8, MD: 3, ML: 19, GF: 35, GA: 59, logo: "china/shenzhen.png" },
        { team: "Wuhan Three Towns", MP: 30, MW: 6, MD: 7, ML: 17, GF: 34, GA: 62, logo: "china/wuhan.png" },
        { team: "Qingdao Hainiu", MP: 30, MW: 5, MD: 10, ML: 15, GF: 35, GA: 48, logo: "china/qingdaohainiu.png" },
        { team: "Meizhou Hakka", MP: 30, MW: 5, MD: 6, ML: 19, GF: 36, GA: 71, logo: "china/meizhou.png" },
        { team: "Changchun Yatai", MP: 30, MW: 4, MD: 7, ML: 19, GF: 26, GA: 52, logo: "china/changchun.png" }
    ],
    fixtures: [
        { home: "Qingdao Hainiu", away: "Yunnan Yukun", date: "2026-06-15" },
        { home: "Shenyang Urban", away: "Shandong Taishan", date: "2026-06-15" },
        { home: "Henan", away: "Shanghai Port", date: "2026-06-15" },
        { home: "Shenzhen Peng City", away: "Chengdu Rongcheng", date: "2026-06-15" },
        { home: "Chongqing Tonglianglong", away: "Tianjin Jinmen Tiger", date: "2026-06-15" },
        { home: "Beijing Guoan", away: "Wuhan Three Towns", date: "2026-06-15" },
        { home: "Qingdao Youth Island", away: "Zhejiang", date: "2026-06-15" },
        { home: "Dalian Yingbo", away: "Shanghai Shenhua", date: "2026-06-15" }
    ]
},

"NBA": {
    id: "nba",
    logo: "nba.png",
    isBasketball: true,
    teams: [
        { rank: 1, team: "Boston Celtics", GP: 82, GW: 64, GL: 18, points_for: 9840, points_against: 8938 },
        { rank: 2, team: "Denver Nuggets", GP: 82, GW: 57, GL: 25, points_for: 9430, points_against: 9020 },
        { rank: 3, team: "LA Lakers", GP: 82, GW: 52, GL: 30, points_for: 9676, points_against: 9184 },
        { rank: 4, team: "Philadelphia 76ers", GP: 82, GW: 54, GL: 28, points_for: 9594, points_against: 9102 },
        { rank: 5, team: "Milwaukee Bucks", GP: 82, GW: 49, GL: 33, points_for: 9758, points_against: 9594 },
        { rank: 6, team: "Golden State Warriors", GP: 82, GW: 46, GL: 36, points_for: 9676, points_against: 9594 },
        { rank: 7, team: "Phoenix Suns", GP: 82, GW: 45, GL: 37, points_for: 9430, points_against: 9266 },
        { rank: 8, team: "Miami Heat", GP: 82, GW: 44, GL: 38, points_for: 9020, points_against: 8938 },
        { rank: 9, team: "New York Knicks", GP: 82, GW: 47, GL: 35, points_for: 9430, points_against: 9184 },
        { rank: 10, team: "Dallas Mavericks", GP: 82, GW: 50, GL: 32, points_for: 9676, points_against: 9512 }
    ],
    fixtures: [
        { home: "Boston Celtics", away: "LA Lakers", date: "2026-06-15" },
        { home: "Denver Nuggets", away: "Milwaukee Bucks", date: "2026-06-15" },
        { home: "Philadelphia 76ers", away: "Phoenix Suns", date: "2026-06-15" },
        { home: "Golden State Warriors", away: "Miami Heat", date: "2026-06-15" },
        { home: "New York Knicks", away: "Dallas Mavericks", date: "2026-06-15" }
    ]
},

"EuroLeague": {
    id: "euroleague",
    logo: "euroleague.png",
    isBasketball: true,
    teams: [
        { rank: 1, team: "Real Madrid", GP: 34, GW: 27, GL: 7, points_for: 2992, points_against: 2686 },
        { rank: 2, team: "Panathinaikos", GP: 34, GW: 23, GL: 11, points_for: 2856, points_against: 2652 },
        { rank: 3, team: "Olympiacos", GP: 34, GW: 22, GL: 12, points_for: 2890, points_against: 2720 },
        { rank: 4, team: "Barcelona", GP: 34, GW: 22, GL: 12, points_for: 2958, points_against: 2788 },
        { rank: 5, team: "Monaco", GP: 34, GW: 21, GL: 13, points_for: 2924, points_against: 2788 },
        { rank: 6, team: "Fenerbahce", GP: 34, GW: 20, GL: 14, points_for: 2822, points_against: 2754 },
        { rank: 7, team: "Maccabi Tel Aviv", GP: 34, GW: 20, GL: 14, points_for: 2856, points_against: 2822 },
        { rank: 8, team: "Partizan", GP: 34, GW: 19, GL: 15, points_for: 2788, points_against: 2754 },
        { rank: 9, team: "Zalgiris Kaunas", GP: 34, GW: 18, GL: 16, points_for: 2720, points_against: 2686 },
        { rank: 10, team: "Anadolu Efes", GP: 34, GW: 17, GL: 17, points_for: 2788, points_against: 2856 }
    ],
    fixtures: [
        { home: "Real Madrid", away: "Barcelona", date: "2026-06-15" },
        { home: "Panathinaikos", away: "Olympiacos", date: "2026-06-15" },
        { home: "Monaco", away: "Fenerbahce", date: "2026-06-15" },
        { home: "Maccabi Tel Aviv", away: "Partizan", date: "2026-06-15" },
        { home: "Anadolu Efes", away: "Zalgiris Kaunas", date: "2026-06-15" }
    ]
},

"Spanish ACB": {
    id: "acb",
    logo: "acb.png",
    isBasketball: true,
    teams: [
        { rank: 1, team: "Real Madrid", GP: 34, GW: 28, GL: 6, points_for: 3026, points_against: 2652 },
        { rank: 2, team: "Barcelona", GP: 34, GW: 26, GL: 8, points_for: 2992, points_against: 2686 },
        { rank: 3, team: "Unicaja", GP: 34, GW: 24, GL: 10, points_for: 2958, points_against: 2720 },
        { rank: 4, team: "Valencia", GP: 34, GW: 21, GL: 13, points_for: 2890, points_against: 2788 },
        { rank: 5, team: "Gran Canaria", GP: 34, GW: 20, GL: 14, points_for: 2890, points_against: 2788 },
        { rank: 6, team: "Baskonia", GP: 34, GW: 19, GL: 15, points_for: 2856, points_against: 2822 },
        { rank: 7, team: "Joventut", GP: 34, GW: 18, GL: 16, points_for: 2822, points_against: 2856 },
        { rank: 8, team: "Murcia", GP: 34, GW: 17, GL: 17, points_for: 2788, points_against: 2856 }
    ],
    fixtures: [
        { home: "Real Madrid", away: "Barcelona", date: "2026-06-15" },
        { home: "Unicaja", away: "Valencia", date: "2026-06-15" },
        { home: "Gran Canaria", away: "Baskonia", date: "2026-06-15" },
        { home: "Joventut", away: "Murcia", date: "2026-06-15" }
    ]
}

};

// ==================== MATCH RESULTS DATA ====================

const matchesData = {
    "English Premier League": [
        { home: "Liverpool", away: "Arsenal", home_score: 2, away_score: 1 },
        { home: "Manchester City", away: "Chelsea", home_score: 3, away_score: 0 },
        { home: "Manchester United", away: "Crystal Palace", home_score: 2, away_score: 1 },
        { home: "Brighton", away: "Nottingham", home_score: 1, away_score: 1 },
        { home: "Fulham", away: "Tottenham", home_score: 2, away_score: 1 },
        { home: "Arsenal", away: "Chelsea", home_score: 2, away_score: 1 },
        { home: "Bournemouth", away: "Brentford", home_score: 0, away_score: 0 },
        { home: "Everton", away: "Burnley", home_score: 2, away_score: 0 },
        { home: "Leeds", away: "Sunderland", home_score: 0, away_score: 1 },
        { home: "Wolves", away: "Liverpool", home_score: 2, away_score: 1 },
        { home: "Brighton", away: "Arsenal", home_score: 0, away_score: 1 },
        { home: "Fulham", away: "West Ham", home_score: 0, away_score: 1 },
        { home: "Manchester City", away: "Nottingham", home_score: 2, away_score: 2 },
        { home: "Aston Villa", away: "Chelsea", home_score: 1, away_score: 4 },
        { home: "Newcastle", away: "Manchester United", home_score: 2, away_score: 1 },
        { home: "Tottenham", away: "Crystal Palace", home_score: 1, away_score: 3 }
    ],
    "Spanish La Liga": [
        { home: "Barcelona", away: "Real Madrid", home_score: 2, away_score: 2 },
        { home: "Atletico Madrid", away: "Real Sociedad", home_score: 3, away_score: 2 },
        { home: "Osasuna", away: "Mallorca", home_score: 2, away_score: 2 },
        { home: "Levante", away: "Girona", home_score: 1, away_score: 1 },
        { home: "Athletic Club", away: "Barcelona", home_score: 0, away_score: 1 }
    ],
    "Italian Serie A": [
        { home: "Sassuolo", away: "Verona", home_score: 3, away_score: 0 },
        { home: "Juventus", away: "Como", home_score: 0, away_score: 2 },
        { home: "Leece", away: "Inter", home_score: 0, away_score: 2 },
        { home: "Cagliari", away: "Lazio", home_score: 0, away_score: 0 },
        { home: "Genoa", away: "Torino", home_score: 3, away_score: 0 },
        { home: "Atalanta", away: "Napoli", home_score: 2, away_score: 1 }
    ],
    "Japanese J1 League": [
        { home: "JEF", away: "Kashiwa", home_score: 2, away_score: 1 },
        { home: "FC Tokyo", away: "Yokohama FM", home_score: 3, away_score: 0 },
        { home: "Urawa Reds", away: "Mito", home_score: 2, away_score: 0 },
        { home: "Kashima Antlers", away: "Tokyo Verdy", home_score: 2, away_score: 0 },
        { home: "Avispa", away: "Nagoya", home_score: 1, away_score: 5 },
        { home: "Okayama", away: "Kyoto", home_score: 1, away_score: 0 },
        { home: "Gamba Osaka", away: "Nagasaki", home_score: 3, away_score: 2 },
        { home: "Yokohama FM", away: "JEF", home_score: 2, away_score: 0 },
        { home: "Kyoto", away: "Cerezo Osaka", home_score: 1, away_score: 2 },
        { home: "Shimizu", away: "Okayama", home_score: 1, away_score: 1 },
        { home: "Kashiwa", away: "Machida", home_score: 0, away_score: 1 },
        { home: "Nagoya", away: "Vissel Kobe", home_score: 0, away_score: 3 },
        { home: "Mito", away: "FC Tokyo", home_score: 1, away_score: 1 },
        { home: "Kashima Antlers", away: "Kawasaki", home_score: 1, away_score: 0 },
        { home: "Nagasaki", away: "Avispa", home_score: 1, away_score: 0 },
        { home: "Cerezo Osaka", away: "Okayama", home_score: 1, away_score: 2 },
        { home: "Vissel Kobe", away: "Gamba Osaka", home_score: 2, away_score: 2 },
        { home: "Mito", away: "Yokohama FM", home_score: 1, away_score: 0 },
        { home: "Avispa", away: "Shimizu", home_score: 1, away_score: 1 },
        { home: "Nagoya", away: "Sanfreece", home_score: 2, away_score: 1 },
        { home: "JEF", away: "FC Tokyo", home_score: 1, away_score: 2 },
        { home: "Nagasaki", away: "Kyoto", home_score: 1, away_score: 2 },
        { home: "Tokyo Verdy", away: "Kawasaki", home_score: 0, away_score: 2 },
        { home: "Machida", away: "Kashima Antlers", home_score: 0, away_score: 3 },
        { home: "Urawa Reds", away: "Kashiwa", home_score: 1, away_score: 1 },
        { home: "Okayama", away: "Nagasaki", home_score: 0, away_score: 1 },
        { home: "Avispa", away: "Gamba Osaka", home_score: 2, away_score: 2 },
        { home: "Shimizu", away: "Sanfreece", home_score: 3, away_score: 1 },
        { home: "Kyoto", away: "Nagoya", home_score: 1, away_score: 1 },
        { home: "Tokyo Verdy", away: "FC Tokyo", home_score: 0, away_score: 0 },
        { home: "Cerezo Osaka", away: "Vissel Kobe", home_score: 1, away_score: 1 },
        { home: "Kashima Antlers", away: "JEF", home_score: 2, away_score: 1 },
        { home: "Kawasaki", away: "Yokohama FM", home_score: 0, away_score: 5 },
        { home: "Kashiwa", away: "Mito", home_score: 3, away_score: 0 },
        { home: "Urawa Reds", away: "Machida", home_score: 1, away_score: 2 },
        { home: "Vissel Kobe", away: "Sanfreece", home_score: 2, away_score: 1 },
        { home: "Machida", away: "Kawasaki", home_score: 1, away_score: 1 },
        { home: "Machida", away: "FC Tokyo", home_score: 2, away_score: 0 },
        { home: "Vissel Kobe", away: "Shimizu", home_score: 2, away_score: 0 },
        { home: "JEF", away: "Tokyo Verdy", home_score: 3, away_score: 2 },
        { home: "Mito", away: "Kashima Antlers", home_score: 1, away_score: 1 },
        { home: "Nagoya", away: "Cerezo Osaka", home_score: 3, away_score: 0 },
        { home: "Gamba Osaka", away: "Kyoto", home_score: 2, away_score: 0 },
        { home: "Nagasaki", away: "Shimizu", home_score: 0, away_score: 3 },
        { home: "Okayama", away: "Vissel Kobe", home_score: 1, away_score: 4 },
        { home: "Kashiwa", away: "Yokohama FM", home_score: 3, away_score: 0 },
        { home: "Kawasaki", away: "Urawa Reds", home_score: 3, away_score: 2 }
    ],
    "Chilean Primera División": [
        { home: "Palestino", away: "La Serena", home_score: 5, away_score: 1 },
        { home: "Coquimbo", away: "Audax Italiano", home_score: 3, away_score: 0 },
        { home: "O'Higgins", away: "Universidad de Concepción", home_score: 0, away_score: 1 },
        { home: "Deportes Limache", away: "Universidad Católica", home_score: 0, away_score: 2 },
        { home: "Huachipato", away: "Unión La Calera", home_score: 3, away_score: 1 },
        { home: "Cobresal", away: "Universidad de Chile", home_score: 1, away_score: 0 },
        { home: "Colo-Colo", away: "Ñublense", home_score: 6, away_score: 2 },
        { home: "Concepción", away: "Everton", home_score: 0, away_score: 2 },
        { home: "Everton", away: "Coquimbo", home_score: 1, away_score: 1 },
        { home: "Audax Italiano", away: "Cobresal", home_score: 2, away_score: 1 },
        { home: "Ñublense", away: "Universidad de Concepción", home_score: 2, away_score: 2 },
        { home: "Unión La Calera", away: "Palestino", home_score: 1, away_score: 2 },
        { home: "Concepción", away: "Huachipato", home_score: 2, away_score: 0 },
        { home: "La Serena", away: "Deportes Limache", home_score: 4, away_score: 1 },
        { home: "Universidad Católica", away: "Colo-Colo", home_score: 1, away_score: 2 },
        { home: "Cobresal", away: "Ñublense", home_score: 0, away_score: 1 },
        { home: "Universidad de Concepción", away: "Unión La Calera", home_score: 0, away_score: 0 },
        { home: "La Serena", away: "Colo-Colo", home_score: 2, away_score: 4 },
        { home: "Deportes Limache", away: "Coquimbo", home_score: 2, away_score: 3 }
    ],
    "Argentine Primera B Metropolitana": [
        { home: "Deportivo Camioneros", away: "Villa San Carlos", home_score: 3, away_score: 0 },
        { home: "Argentino de Merlo", away: "San Martín Burzaco", home_score: 0, away_score: 1 },
        { home: "Dep. Armenio", away: "Argentino de Merlo", home_score: 2, away_score: 0 },
        { home: "Flandria", away: "Arsenal Sarandi", home_score: 0, away_score: 0 },
        { home: "Dock Sud", away: "Real Pilar", home_score: 2, away_score: 0 },
        { home: "Brown (A)", away: "Talleres Remedios", home_score: 1, away_score: 2 },
        { home: "Deportivo Merlo", away: "Liniers", home_score: 0, away_score: 0 },
        { home: "Comunicaciones", away: "UAI Urquiza", home_score: 3, away_score: 0 },
        { home: "Ituzaingó", away: "Laferrere", home_score: 0, away_score: 2 },
        { home: "Sportivo Italiano", away: "San Martín Burzaco", home_score: 1, away_score: 2 },
        { home: "Defensores Unidos", away: "Dálmine", home_score: 2, away_score: 1 },
        { home: "Argentino Quilmes", away: "Excursionistas", home_score: 2, away_score: 2 },
        { home: "Comunicaciones", away: "Dep. Armenio", home_score: 0, away_score: 1 },
        { home: "Dock Sud", away: "Brown (A)", home_score: 0, away_score: 1 },
        { home: "Real Pilar", away: "UAI Urquiza", home_score: 2, away_score: 1 },
        { home: "Liniers", away: "Dálmine", home_score: 1, away_score: 0 },
        { home: "Deportivo Camioneros", away: "Talleres Remedios", home_score: 1, away_score: 4 },
        { home: "Sportivo Italiano", away: "Argentino de Merlo", home_score: 0, away_score: 2 },
        { home: "Villa San Carlos", away: "Excursionistas", home_score: 0, away_score: 2 },
        { home: "Defensores Unidos", away: "Flandria", home_score: 1, away_score: 0 }
    ],
	
	"Argentine Reserve League - Group A": [
    // Round 16
    { home: "Banfield 2", away: "Sarmiento Junin 2", home_score: 2, away_score: 1, date: "2026-06-02" },
    { home: "Tigre 2", away: "River Plate 2", home_score: 0, away_score: 2, date: "2026-06-02" },
    
    // Round 15
    { home: "River Plate 2", away: "San Lorenzo 2", home_score: 1, away_score: 1, date: "2026-05-29" },
    { home: "Aldosivi 2", away: "Talleres Cordoba 2", home_score: 0, away_score: 2, date: "2026-05-28" },
    { home: "Gimnasia L.P. 2", away: "Barracas Central 2", home_score: 0, away_score: 0, date: "2026-05-28" },
    { home: "Lanus 2", away: "Platense 2", home_score: 0, away_score: 2, date: "2026-05-28" },
    { home: "Sarmiento Junin 2", away: "Rosario Central 2", home_score: 0, away_score: 2, date: "2026-05-28" },
    { home: "Union de Santa Fe 2", away: "Gimnasia Mendoza 2", home_score: 0, away_score: 2, date: "2026-05-28" },
    { home: "Atl. Tucuman 2", away: "Godoy Cruz 2", home_score: 3, away_score: 1, date: "2026-05-27" },
    { home: "Velez Sarsfield 2", away: "Instituto 2", home_score: 2, away_score: 3, date: "2026-05-27" },
    { home: "Argentinos Jrs 2", away: "Banfield 2", home_score: 2, away_score: 0, date: "2026-05-26" },
    { home: "Racing Club 2", away: "Tigre 2", home_score: 2, away_score: 1, date: "2026-05-26" },
    
    // Round 14
    { home: "Talleres Cordoba 2", away: "Gimnasia L.P. 2", home_score: 1, away_score: 2, date: "2026-05-22" },
    { home: "Barracas Central 2", away: "Union de Santa Fe 2", home_score: 1, away_score: 1, date: "2026-05-21" },
    { home: "Gimnasia Mendoza 2", away: "Atl. Tucuman 2", home_score: 1, away_score: 2, date: "2026-05-21" },
    { home: "Instituto 2", away: "Godoy Cruz 2", home_score: 2, away_score: 1, date: "2026-05-21" },
    { home: "Velez Sarsfield 2", away: "River Plate 2", home_score: 1, away_score: 0, date: "2026-05-21" },
    { home: "Rosario Central 2", away: "Argentinos Jrs 2", home_score: 1, away_score: 2, date: "2026-05-20" },
    { home: "Tigre 2", away: "Sarmiento Junin 2", home_score: 1, away_score: 3, date: "2026-05-20" },
    { home: "Banfield 2", away: "Aldosivi 2", home_score: 0, away_score: 0, date: "2026-05-19" },
    { home: "San Lorenzo 2", away: "Racing Club 2", home_score: 1, away_score: 2, date: "2026-05-19" },
    
    // Round 13
    { home: "Godoy Cruz 2", away: "Gimnasia Mendoza 2", home_score: 2, away_score: 3, date: "2026-05-14" },
    { home: "River Plate 2", away: "Instituto 2", home_score: 1, away_score: 0, date: "2026-05-14" },
    { home: "Sarmiento Junin 2", away: "San Lorenzo 2", home_score: 1, away_score: 2, date: "2026-05-14" },
    { home: "Union de Santa Fe 2", away: "Talleres Cordoba 2", home_score: 2, away_score: 1, date: "2026-05-14" },
    { home: "Argentinos Jrs 2", away: "Tigre 2", home_score: 2, away_score: 0, date: "2026-05-13" },
    { home: "Atl. Tucuman 2", away: "Barracas Central 2", home_score: 3, away_score: 2, date: "2026-05-13" },
    { home: "Aldosivi 2", away: "Rosario Central 2", home_score: 1, away_score: 0, date: "2026-05-12" },
    { home: "Gimnasia L.P. 2", away: "Banfield 2", home_score: 2, away_score: 0, date: "2026-05-12" },
    { home: "Racing Club 2", away: "Velez Sarsfield 2", home_score: 1, away_score: 1, date: "2026-05-12" },
    
    // Round 12
    { home: "Banfield 2", away: "Union de Santa Fe 2", home_score: 1, away_score: 1, date: "2026-05-07" },
    { home: "Barracas Central 2", away: "Godoy Cruz 2", home_score: 1, away_score: 0, date: "2026-05-07" },
    { home: "Talleres Cordoba 2", away: "Atl. Tucuman 2", home_score: 5, away_score: 0, date: "2026-05-07" },
    { home: "Tigre 2", away: "Aldosivi 2", home_score: 2, away_score: 1, date: "2026-05-07" },
    { home: "River Plate 2", away: "Racing Club 2", home_score: 2, away_score: 2, date: "2026-05-06" },
    { home: "Rosario Central 2", away: "Gimnasia L.P. 2", home_score: 0, away_score: 0, date: "2026-05-06" },
    { home: "San Lorenzo 2", away: "Argentinos Jrs 2", home_score: 2, away_score: 2, date: "2026-05-06" },
    { home: "Velez Sarsfield 2", away: "Sarmiento Junin 2", home_score: 4, away_score: 0, date: "2026-05-06" },
    { home: "Instituto 2", away: "Gimnasia Mendoza 2", home_score: 0, away_score: 0, date: "2026-05-05" }
],

"Argentine Reserve League - Group B": [
    // Round 16
    { home: "Colon Santa Fe 2", away: "Huracan 2", home_score: 3, away_score: 1, date: "2026-06-02" },
    { home: "Ferro 2", away: "Estudiantes Rio Cuarto 2", home_score: 4, away_score: 1, date: "2026-06-02" },
    { home: "Independiente 2", away: "Newells Old Boys 2", home_score: 1, away_score: 0, date: "2026-06-02" },
    { home: "Quilmes 2", away: "Deportivo Riestra 2", home_score: 1, away_score: 0, date: "2026-06-02" },
    
    // Round 15
    { home: "Belgrano 2", away: "Quilmes 2", home_score: 1, away_score: 0, date: "2026-05-27" },
    { home: "Deportivo Riestra 2", away: "Estudiantes L.P. 2", home_score: 1, away_score: 2, date: "2026-05-27" },
    { home: "Ind. Rivadavia 2", away: "Central Cordoba 2", home_score: 2, away_score: 1, date: "2026-05-27" },
    { home: "Newells Old Boys 2", away: "Atl. Rafaela 2", home_score: 3, away_score: 0, date: "2026-05-27" },
    { home: "Defensa y Justicia 2", away: "Independiente 2", home_score: 1, away_score: 1, date: "2026-05-26" },
    { home: "Estudiantes Rio Cuarto 2", away: "Boca Juniors 2", home_score: 0, away_score: 2, date: "2026-05-26" },
    { home: "Huracan 2", away: "Ferro 2", home_score: 2, away_score: 0, date: "2026-05-26" },
    { home: "San Martin S.J. 2", away: "Colon Santa Fe 2", home_score: 1, away_score: 1, date: "2026-05-26" },
    
    // Round 14
    { home: "Boca Juniors 2", away: "Huracan 2", home_score: 1, away_score: 0, date: "2026-05-21" },
    { home: "Estudiantes L.P. 2", away: "Belgrano 2", home_score: 3, away_score: 1, date: "2026-05-21" },
    { home: "Atl. Rafaela 2", away: "Defensa y Justicia 2", home_score: 2, away_score: 4, date: "2026-05-20" },
    { home: "Central Cordoba 2", away: "Deportivo Riestra 2", home_score: 1, away_score: 0, date: "2026-05-20" },
    { home: "Platense 2", away: "Newells Old Boys 2", home_score: 1, away_score: 1, date: "2026-05-20" },
    { home: "Colon Santa Fe 2", away: "Ferro 2", home_score: 0, away_score: 1, date: "2026-05-19" },
    { home: "Independiente 2", away: "Estudiantes Rio Cuarto 2", home_score: 5, away_score: 0, date: "2026-05-19" },
    { home: "Quilmes 2", away: "Lanus 2", home_score: 0, away_score: 2, date: "2026-05-19" },
    { home: "San Martin S.J. 2", away: "Ind. Rivadavia 2", home_score: 0, away_score: 2, date: "2026-05-19" },
    
    // Round 13
    { home: "Deportivo Riestra 2", away: "San Martin S.J. 2", home_score: 2, away_score: 2, date: "2026-05-14" },
    { home: "Huracan 2", away: "Independiente 2", home_score: 1, away_score: 0, date: "2026-05-14" },
    { home: "Lanus 2", away: "Estudiantes L.P. 2", home_score: 1, away_score: 4, date: "2026-05-14" },
    { home: "Ferro 2", away: "Boca Juniors 2", home_score: 0, away_score: 0, date: "2026-05-13" },
    { home: "Ind. Rivadavia 2", away: "Colon Santa Fe 2", home_score: 1, away_score: 2, date: "2026-05-13" },
    { home: "Defensa y Justicia 2", away: "Platense 2", home_score: 4, away_score: 0, date: "2026-05-12" },
    { home: "Estudiantes Rio Cuarto 2", away: "Atl. Rafaela 2", home_score: 0, away_score: 2, date: "2026-05-12" },
    { home: "Newells Old Boys 2", away: "Quilmes 2", home_score: 2, away_score: 0, date: "2026-05-12" }
],
	
    "Chinese Super League": [
        { home: "Qingdao Youth Island", away: "Tianjin Jinmen Tiger", home_score: 1, away_score: 1 },
        { home: "Shandong Taishan", away: "Shanghai Shenhua", home_score: 4, away_score: 1 },
        { home: "Shenyang Urban", away: "Chengdu Rongcheng", home_score: 0, away_score: 1 },
        { home: "Chongqing Tonglianglong", away: "Henan", home_score: 1, away_score: 1 },
        { home: "Wuhan Three Towns", away: "Qingdao Hainiu", home_score: 1, away_score: 3 },
        { home: "Beijing Guoan", away: "Dalian Yingbo", home_score: 3, away_score: 0 },
        { home: "Shanghai Port", away: "Shenzhen Peng City", home_score: 1, away_score: 1 },
        { home: "Yunnan Yukun", away: "Zhejiang", home_score: 1, away_score: 2 },
        { home: "Shanghai Shenhua", away: "Chongqing Tonglianglong", home_score: 2, away_score: 2 },
        { home: "Chengdu Rongcheng", away: "Henan", home_score: 3, away_score: 0 },
        { home: "Qingdao Youth Island", away: "Wuhan Three Towns", home_score: 1, away_score: 1 },
        { home: "Shenzhen Peng City", away: "Shandong Taishan", home_score: 1, away_score: 2 },
        { home: "Shenyang Urban", away: "Yunnan Yukun", home_score: 1, away_score: 2 },
        { home: "Zhejiang", away: "Tianjin Jinmen Tiger", home_score: 1, away_score: 1 },
        { home: "Beijing Guoan", away: "Shanghai Port", home_score: 2, away_score: 2 },
        { home: "Qingdao Hainiu", away: "Dalian Yingbo", home_score: 3, away_score: 1 },
        { home: "Henan", away: "Shenzhen Peng City", home_score: 1, away_score: 0 },
        { home: "Tianjin Jinmen Tiger", away: "Chengdu Rongcheng", home_score: 1, away_score: 2 },
        { home: "Shanghai Port", away: "Zhejiang", home_score: 2, away_score: 2 },
        { home: "Dalian Yingbo", away: "Qingdao Youth Island", home_score: 2, away_score: 3 },
        { home: "Beijing Guoan", away: "Qingdao Hainiu", home_score: 4, away_score: 2 },
        { home: "Wuhan Three Towns", away: "Shenyang Urban", home_score: 2, away_score: 2 },
        { home: "Shandong Taishan", away: "Chongqing Tonglianglong", home_score: 3, away_score: 1 },
        { home: "Yunnan Yukun", away: "Shanghai Shenhua", home_score: 1, away_score: 0 },
        { home: "Tianjin Jinmen Tiger", away: "Henan", home_score: 1, away_score: 2 },
        { home: "Shenzhen Peng City", away: "Dalian Yingbo", home_score: 1, away_score: 1 },
        { home: "Qingdao Youth Island", away: "Beijing Guoan", home_score: 1, away_score: 1 },
        { home: "Chengdu Rongcheng", away: "Shanghai Port", home_score: 0, away_score: 1 },
        { home: "Shenyang Urban", away: "Qingdao Hainiu", home_score: 2, away_score: 1 },
        { home: "Shanghai Shenhua", away: "Wuhan Three Towns", home_score: 2, away_score: 2 },
        { home: "Chongqing Tonglianglong", away: "Yunnan Yukun", home_score: 0, away_score: 0 },
        { home: "Zhejiang", away: "Shandong Taishan", home_score: 4, away_score: 1 },
        { home: "Shanghai Port", away: "Tianjin Jinmen Tiger", home_score: 1, away_score: 1 },
        { home: "Beijing Guoan", away: "Henan", home_score: 1, away_score: 2 },
        { home: "Dalian Yingbo", away: "Chengdu Rongcheng", home_score: 2, away_score: 0 },
        { home: "Qingdao Hainiu", away: "Chongqing Tonglianglong", home_score: 0, away_score: 1 },
        { home: "Yunnan Yukun", away: "Qingdao Youth Island", home_score: 2, away_score: 3 },
        { home: "Shandong Taishan", away: "Wuhan Three Towns", home_score: 3, away_score: 3 },
        { home: "Zhejiang", away: "Shenyang Urban", home_score: 0, away_score: 5 },
        { home: "Shanghai Shenhua", away: "Shenzhen Peng City", home_score: 1, away_score: 2 },
        { home: "Shenyang Urban", away: "Shanghai Port", home_score: 3, away_score: 2 },
        { home: "Qingdao Youth Island", away: "Shanghai Shenhua", home_score: 2, away_score: 2 },
        { home: "Henan", away: "Zhejiang", home_score: 0, away_score: 2 },
        { home: "Chengdu Rongcheng", away: "Shandong Taishan", home_score: 1, away_score: 0 },
        { home: "Chongqing Tonglianglong", away: "Beijing Guoan", home_score: 2, away_score: 3 },
        { home: "Shenzhen Peng City", away: "Qingdao Hainiu", home_score: 3, away_score: 2 },
        { home: "Tianjin Jinmen Tiger", away: "Dalian Yingbo", home_score: 1, away_score: 0 },
        { home: "Wuhan Three Towns", away: "Yunnan Yukun", home_score: 1, away_score: 1 }
    ]
};

console.log("✅ Matches data loaded from data.js");
console.log("✅ Data loaded successfully!", Object.keys(leaguesData).length, "leagues");