// ==================== COMPLETE LEAGUES DATA ====================
// ONLY data declarations - NO functions or thresholds here

const leaguesData = {
    "English Premier League": {
        id: "epl",
        logo: "epl.png",
        isBasketball: false,
        teams: [
            { team: "Liverpool", MP: 38, MW: 25, MD: 9, GF: 86, GA: 41 },
            { team: "Arsenal", MP: 38, MW: 20, MD: 14, GF: 69, GA: 34 },
            { team: "Manchester City", MP: 38, MW: 21, MD: 8, GF: 72, GA: 44 },
            { team: "Chelsea", MP: 38, MW: 20, MD: 9, GF: 64, GA: 43 },
            { team: "Newcastle", MP: 38, MW: 20, MD: 6, GF: 68, GA: 47 },
            { team: "Aston Villa", MP: 38, MW: 19, MD: 9, GF: 58, GA: 51 },
            { team: "Brighton", MP: 38, MW: 16, MD: 13, GF: 66, GA: 59 },
            { team: "Nottingham", MP: 38, MW: 19, MD: 8, GF: 58, GA: 46 },
            { team: "Bournemouth", MP: 38, MW: 15, MD: 11, GF: 58, GA: 46 },
            { team: "Brentford", MP: 38, MW: 16, MD: 8, GF: 66, GA: 57 },
            { team: "Fulham", MP: 38, MW: 15, MD: 9, GF: 54, GA: 54 },
            { team: "Crystal Palace", MP: 38, MW: 13, MD: 14, GF: 51, GA: 51 },
            { team: "Everton", MP: 38, MW: 11, MD: 5, GF: 42, GA: 44 },
            { team: "West Ham", MP: 38, MW: 11, MD: 10, GF: 46, GA: 62 },
            { team: "Manchester United", MP: 38, MW: 11, MD: 9, GF: 44, GA: 54 },
            { team: "Wolves", MP: 38, MW: 12, MD: 6, GF: 54, GA: 69 },
            { team: "Tottenham", MP: 38, MW: 11, MD: 5, GF: 64, GA: 65 },
            { team: "Leicester", MP: 38, MW: 6, MD: 7, GF: 33, GA: 80 },
            { team: "Ipswich", MP: 38, MW: 4, MD: 10, GF: 36, GA: 82 },
            { team: "Southampton", MP: 38, MW: 2, MD: 6, GF: 26, GA: 86 }
        ],
        fixtures: [
            ["Manchester City", "Aston Villa"],
            ["Brighton", "Manchester United"],
            ["Fulham", "Newcastle"],
            ["Tottenham", "Everton"],
            ["Liverpool", "Brentford"],
            ["Nottingham", "Bournemouth"],
            ["West Ham", "Leeds"],
            ["Crystal Palace", "Arsenal"]
        ]
    },

    "Spanish La Liga": {
        id: "laliga",
        logo: "laliga.png",
        isBasketball: false,
        teams: [
            { team: "Barcelona", MP: 38, MW: 28, MD: 4, GF: 102, GA: 39 },
            { team: "Real Madrid", MP: 38, MW: 26, MD: 6, GF: 78, GA: 38 },
            { team: "Atletico Madrid", MP: 38, MW: 22, MD: 10, GF: 65, GA: 30 },
            { team: "Athletic Club", MP: 38, MW: 19, MD: 13, GF: 54, GA: 29 },
            { team: "Villarreal", MP: 38, MW: 20, MD: 10, GF: 71, GA: 51 },
            { team: "Real Betis", MP: 38, MW: 16, MD: 12, GF: 57, GA: 50 },
            { team: "Celta Vigo", MP: 38, MW: 16, MD: 7, GF: 59, GA: 57 },
            { team: "Rayo Vallecano", MP: 38, MW: 13, MD: 13, GF: 41, GA: 45 },
            { team: "Osasuna", MP: 38, MW: 12, MD: 16, GF: 48, GA: 52 },
            { team: "Mallorca", MP: 38, MW: 13, MD: 9, GF: 45, GA: 44 },
            { team: "Real Sociedad", MP: 38, MW: 13, MD: 7, GF: 35, GA: 46 },
            { team: "Valencia", MP: 38, MW: 11, MD: 13, GF: 44, GA: 54 },
            { team: "Getafe", MP: 38, MW: 11, MD: 9, GF: 34, GA: 39 },
            { team: "Espanyol", MP: 38, MW: 11, MD: 9, GF: 40, GA: 51 },
            { team: "Alaves", MP: 38, MW: 10, MD: 12, GF: 38, GA: 48 },
            { team: "Girona", MP: 38, MW: 11, MD: 8, GF: 44, GA: 60 },
            { team: "Sevilla", MP: 38, MW: 10, MD: 11, GF: 42, GA: 55 },
            { team: "Leganes", MP: 38, MW: 9, MD: 13, GF: 39, GA: 56 },
            { team: "Las Palmas", MP: 38, MW: 8, MD: 8, GF: 40, GA: 61 },
            { team: "Valladolid", MP: 38, MW: 4, MD: 4, GF: 26, GA: 90 }
        ],
        fixtures: [
            ["Valencia", "Barcelona"],
            ["Real Betis", "Levante"],
            ["Real Madrid", "Athletic Club"],
            ["Alaves", "Rayo Vallecano"],
            ["Girona", "Elche"],
            ["Getafe", "Osasuna"],
            ["Celta Vigo", "Sevilla"],
            ["Mallorca", "Oviedo"],
            ["Espanyol", "Real Sociedad"],
            ["Villarreal", "Atletico Madrid"]
        ]
    },

    "Italian Serie A": {
        id: "seriea",
        logo: "seriea.png",
        isBasketball: false,
        teams: [
            { team: "Napoli", MP: 38, MW: 24, MD: 10, GF: 59, GA: 27 },
            { team: "Inter", MP: 38, MW: 24, MD: 9, GF: 79, GA: 35 },
            { team: "Atalanta", MP: 38, MW: 22, MD: 8, GF: 78, GA: 38 },
            { team: "Juventus", MP: 38, MW: 18, MD: 16, GF: 58, GA: 35 },
            { team: "Roma", MP: 38, MW: 20, MD: 9, GF: 56, GA: 35 },
            { team: "Fiorentina", MP: 38, MW: 19, MD: 8, GF: 60, GA: 41 },
            { team: "Lazio", MP: 38, MW: 18, MD: 11, GF: 61, GA: 49 },
            { team: "Milan", MP: 38, MW: 18, MD: 9, GF: 61, GA: 43 },
            { team: "Bologna", MP: 38, MW: 16, MD: 14, GF: 57, GA: 47 },
            { team: "Como", MP: 38, MW: 13, MD: 10, GF: 49, GA: 52 },
            { team: "Torino", MP: 38, MW: 10, MD: 14, GF: 39, GA: 45 },
            { team: "Udinese", MP: 38, MW: 12, MD: 8, GF: 41, GA: 56 },
            { team: "Genoa", MP: 38, MW: 10, MD: 13, GF: 49, GA: 12 },
            { team: "Verona", MP: 38, MW: 10, MD: 7, GF: 34, GA: 66 },
            { team: "Cagliari", MP: 38, MW: 9, MD: 9, GF: 40, GA: 56 },
            { team: "Parma", MP: 38, MW: 7, MD: 15, GF: 44, GA: 58 },
            { team: "Leece", MP: 38, MW: 8, MD: 10, GF: 27, GA: 58 },
            { team: "Empoli", MP: 38, MW: 6, MD: 13, GF: 33, GA: 59 },
            { team: "Venezia", MP: 38, MW: 5, MD: 14, GF: 32, GA: 56 },
            { team: "Monza", MP: 38, MW: 3, MD: 9, GF: 28, GA: 69 }
        ],
        fixtures: [
            ["Fiorentina", "Atalanta"],
            ["Bologna", "Inter"],
            ["Lazio", "Pisa"],
            ["Parma", "Sassuolo"],
            ["Napoli", "Udinese"],
            ["Verona", "Roma"],
            ["Leece", "Genoa"],
            ["Milan", "Cagliari"],
            ["Torino", "Juventus"],
            ["Cremonese", "Como"]
        ]
    },

    "French Ligue 1": {
        id: "ligue1",
        logo: "ligue1.png",
        isBasketball: false,
        teams: [
            { team: "PSG", MP: 34, MW: 26, MD: 6, GF: 92, GA: 35 },
            { team: "Marseille", MP: 34, MW: 20, MD: 5, GF: 74, GA: 47 },
            { team: "Monaco", MP: 34, MW: 18, MD: 7, GF: 63, GA: 41 },
            { team: "Nice", MP: 34, MW: 17, MD: 9, GF: 66, GA: 41 },
            { team: "Lille", MP: 34, MW: 17, MD: 9, GF: 52, GA: 36 },
            { team: "Lyon", MP: 34, MW: 17, MD: 6, GF: 65, GA: 46 },
            { team: "Strasbourg", MP: 34, MW: 16, MD: 9, GF: 56, GA: 44 },
            { team: "Lens", MP: 34, MW: 15, MD: 7, GF: 42, GA: 39 },
            { team: "Brest", MP: 34, MW: 15, MD: 5, GF: 52, GA: 59 },
            { team: "Toulouse", MP: 34, MW: 11, MD: 9, GF: 44, GA: 43 },
            { team: "Auxerre", MP: 34, MW: 11, MD: 9, GF: 48, GA: 51 },
            { team: "Rennes", MP: 34, MW: 13, MD: 12, GF: 51, GA: 50 },
            { team: "Nantes", MP: 34, MW: 8, MD: 12, GF: 48, GA: 51 },
            { team: "Angers", MP: 34, MW: 10, MD: 6, GF: 32, GA: 53 },
            { team: "Le Havre", MP: 34, MW: 10, MD: 4, GF: 40, GA: 71 },
            { team: "Reims", MP: 34, MW: 8, MD: 9, GF: 33, GA: 47 },
            { team: "St.Etienne", MP: 34, MW: 8, MD: 6, GF: 30, GA: 77 },
            { team: "Montpellier", MP: 34, MW: 4, MD: 4, GF: 23, GA: 79 }
        ],
        fixtures: [
            ["Nantes", "Marseille"],
            ["PSG", "Lorient"],
            ["Metz", "Monaco"],
            ["Nice", "Lens"],
            ["Lille", "Le Havre"],
            ["Strasbourg", "Toulouse"],
            ["Auxerre", "Angers"],
            ["Paris", "Brest"],
            ["Lyon", "Rennes"]
        ]
    },

    "German Bundesliga": {
        id: "bundesliga",
        logo: "bundesliga.png",
        isBasketball: false,
        teams: [
            { team: "Bayern", MP: 34, MW: 25, MD: 7, GF: 99, GA: 32 },
            { team: "Leverkusen", MP: 34, MW: 19, MD: 12, GF: 72, GA: 43 },
            { team: "Frankfurt", MP: 34, MW: 17, MD: 9, GF: 46, GA: 22 },
            { team: "Dortmund", MP: 34, MW: 17, MD: 6, GF: 71, GA: 51 },
            { team: "Freiburg", MP: 34, MW: 16, MD: 7, GF: 49, GA: 53 },
            { team: "Mainz", MP: 34, MW: 14, MD: 10, GF: 55, GA: 43 },
            { team: "Leipzig", MP: 34, MW: 13, MD: 12, GF: 53, GA: 48 },
            { team: "Werder", MP: 34, MW: 14, MD: 9, GF: 54, GA: 57 },
            { team: "Stuttgart", MP: 34, MW: 14, MD: 8, GF: 64, GA: 53 },
            { team: "Monchengladbach", MP: 34, MW: 13, MD: 6, GF: 55, GA: 57 },
            { team: "Wolfsburg", MP: 34, MW: 11, MD: 10, GF: 56, GA: 54 },
            { team: "Augsburg", MP: 34, MW: 11, MD: 10, GF: 35, GA: 51 },
            { team: "Union Berlin", MP: 34, MW: 10, MD: 10, GF: 35, GA: 51 },
            { team: "St. Pauli", MP: 34, MW: 8, MD: 8, GF: 28, GA: 41 },
            { team: "Hoffenheim", MP: 34, MW: 7, MD: 11, GF: 46, GA: 68 },
            { team: "Heidenheim", MP: 34, MW: 8, MD: 5, GF: 37, GA: 64 },
            { team: "Holstein Kiel", MP: 34, MW: 6, MD: 7, GF: 49, GA: 80 },
            { team: "Bochum", MP: 34, MW: 6, MD: 7, GF: 33, GA: 67 }
        ],
        fixtures: [
            ["Frankfurt", "Hamburger"],
            ["Hoffenheim", "Stuttgart"],
            ["Bayern", "Heidenheim"],
            ["Werder", "Augsburg"],
            ["Union Berlin", "Koln"],
            ["Leverkusen", "Leipzig"],
            ["St. Pauli", "Mainz"],
            ["Monchengladbach", "Dortmund"],
            ["Freiburg", "Wolfsburg"]
        ]
    },
	"Belgian Challenger Pro League": {
    id: "belgium-challenger",
    logo: "belgium-challenger.png",
    isBasketball: false,
    teams: [
        { team: "Zulte Waregem", MP: 28, MW: 18, MD: 5, GF: 55, GA: 30 },
        { team: "La Louviere", MP: 28, MW: 17, MD: 8, GF: 50, GA: 24 },
        { team: "Daring Brussels", MP: 34, MW: 17, MD: 6, GF: 42, GA: 21 },
        { team: "Beveren", MP: 28, MW: 14, MD: 9, GF: 41, GA: 47 },
        { team: "Patro Eisden", MP: 28, MW: 13, MD: 10, GF: 51, GA: 28 },
        { team: "Club NXT", MP: 28, MW: 14, MD: 5, GF: 46, GA: 35 },
        { team: "Lokeren-Temse", MP: 28, MW: 12, MD: 5, GF: 32, GA: 35 },
        { team: "Lierse K", MP: 28, MW: 11, MD: 7, GF: 40, GA: 35 },
        { team: "Liege", MP: 28, MW: 9, MD: 7, GF: 38, GA: 44 },
        { team: "Eupen", MP: 28, MW: 8, MD: 6, GF: 38, GA: 47 },
        { team: "Lommel", MP: 28, MW: 8, MD: 5, GF: 32, GA: 46 },
        { team: "Francs Borains", MP: 28, MW: 8, MD: 4, GF: 29, GA: 50 },
        { team: "RSCA Futures", MP: 28, MW: 5, MD: 8, GF: 41, GA: 54 },
        { team: "Seraing", MP: 28, MW: 3, MD: 10, GF: 28, GA: 55 },
        { team: "Jong Genk", MP: 28, MW: 3, MD: 5, GF: 30, GA: 62 }
    ],
    fixtures: [
        ["Liege", "Eupen"],
        ["Beerschot", "Lommel"],
        ["Kotrijk", "Daring Brussels"],
        ["Patro Eisden", "Francs Borains"],
        ["Jong Genk", "Jong Gent"],
        ["Lierse K", "Lokeren-Temse"],
        ["Seraing", "Beveren"]
    ]
},

"Portuguese Liga 2": {
    id: "portugal-liga2",
    logo: "portugal-liga2.png",
    isBasketball: false,
    teams: [
        { team: "Marítimo", MP: 34, MW: 20, MD: 6, GF: 50, GA: 29 },
        { team: "Académico", MP: 34, MW: 17, MD: 8, GF: 58, GA: 33 },
        { team: "Torreense", MP: 34, MW: 18, MD: 5, GF: 46, GA: 33 },
        { team: "Vizela", MP: 34, MW: 14, MD: 9, GF: 39, GA: 40 },
        { team: "Porto B", MP: 34, MW: 15, MD: 6, GF: 41, GA: 42 },
        { team: "UD Leiria", MP: 33, MW: 13, MD: 10, GF: 50, GA: 44 },
        { team: "Leixoes", MP: 33, MW: 14, MD: 5, GF: 44, GA: 54 },
        { team: "Feirense", MP: 33, MW: 12, MD: 9, GF: 35, GA: 38 },
        { team: "Chaves", MP: 34, MW: 13, MD: 6, GF: 42, GA: 40 },
        { team: "Benfica B", MP: 34, MW: 11, MD: 11, GF: 43, GA: 44 },
        { team: "Felgueiras", MP: 34, MW: 11, MD: 11, GF: 31, GA: 38 },
        { team: "Lusitania Lourosa", MP: 33, MW: 11, MD: 10, GF: 43, GA: 50 },
        { team: "Sporting CP B", MP: 34, MW: 13, MD: 3, GF: 41, GA: 34 },
        { team: "Penafiel", MP: 33, MW: 11, MD: 8, GF: 36, GA: 37 },
        { team: "Farense", MP: 33, MW: 10, MD: 10, GF: 31, GA: 36 },
        { team: "Portimonense", MP: 33, MW: 10, MD: 7, GF: 38, GA: 49 },
        { team: "Pacos Ferreira", MP: 33, MW: 8, MD: 12, GF: 32, GA: 47 },
        { team: "Oliveirense", MP: 34, MW: 8, MD: 10, GF: 34, GA: 46 }
    ],
    fixtures: [
        ["Panfiel", "Farense"],
        ["Acadamico", "Vizela"],
        ["Chaves", "Benfica B"],
        ["Portimonense", "Oliveirense Borains"],
        ["Pacos Ferreira", "Felgueiras Gent"],
        ["Leixoes", "Lousitania Lourosa"],
        ["Chaves", "Feirense"]
    ]
},

"MLS Eastern Conference": {
    id: "mls-east",
    logo: "mls/mlslogo.jpg",
    isBasketball: false,
    teams: [
        { team: "Philadelphia", MP: 34, MW: 20, MD: 6, GF: 57, GA: 35, logo: "mls/philadelphialogo.png" },
        { team: "Cincinnati", MP: 34, MW: 20, MD: 5, GF: 52, GA: 40, logo: "mls/cincinnatlogo.png" },
        { team: "Inter Miami", MP: 34, MW: 19, MD: 8, GF: 81, GA: 55, logo: "mls/intermiamilogo.png" },
        { team: "Charlotte", MP: 34, MW: 19, MD: 2, GF: 55, GA: 46, logo: "mls/charlottelogo.png" },
        { team: "New York", MP: 34, MW: 17, MD: 5, GF: 50, GA: 44, logo: "mls/newyorklogo.png" },
        { team: "Nashville", MP: 34, MW: 16, MD: 6, GF: 58, GA: 45, logo: "mls/nashvillelogo.png" },
        { team: "Columbus", MP: 34, MW: 14, MD: 12, GF: 55, GA: 41, logo: "mls/columbuslogo.png" },
        { team: "Chicago", MP: 34, MW: 15, MD: 8, GF: 68, GA: 60, logo: "mls/chicagologo.png" },
        { team: "Orlando", MP: 34, MW: 14, MD: 11, GF: 63, GA: 51, logo: "mls/orlandologo.png" },
        { team: "NY Red Bulls", MP: 34, MW: 12, MD: 7, GF: 48, GA: 47, logo: "mls/nyredbullslogo.png" },
        { team: "New England", MP: 34, MW: 9, MD: 9, GF: 44, GA: 51, logo: "mls/newenglandlogo.png" },
        { team: "Toronto", MP: 34, MW: 6, MD: 14, GF: 37, GA: 44, logo: "mls/torontologo.png" },
        { team: "Montreal", MP: 34, MW: 6, MD: 10, GF: 34, GA: 60, logo: "mls/monteallogo.png" },
        { team: "Atlanta", MP: 34, MW: 5, MD: 13, GF: 38, GA: 63, logo: "mls/atlantalogo.png" }
    ],
    fixtures: [
        ["St. Louis", "Austin"],
        ["Minnesota", "Real Salt Lake"],
        ["Real Salt Lake", "Portland"],
        ["Cincinnati", "Orlando"],
        ["Charlotte", "New England"],
        ["DC United", "Montreal"],
        ["Chicago", "Toronto"],
        ["Nashville", "New York City"],
        ["Sporting KC", "NY Red Bulls"],
        ["San Diego", "Vancouver"],
        ["Colorado", "Dallas"],
        ["Portland ", "San Jose"],
        ["Columbus", "Atlanta"],
        ["Inter Miami", "Philadelphia"],
        ["LAFC", "Seattle"]
    ]
},

"MLS Western Conference": {
    id: "mls-west",
    logo: "mls/mlslogo.jpg",
    isBasketball: false,
    teams: [
        { team: "DC United", MP: 34, MW: 5, MD: 11, GF: 30, GA: 66, logo: "mls/dcunitedlogo.png" },
        { team: "San Diego", MP: 34, MW: 19, MD: 6, GF: 64, GA: 41, logo: "mls/sandiegologo.jpg" },
        { team: "Vancouver", MP: 34, MW: 18, MD: 9, GF: 66, GA: 38, logo: "mls/vancouverlogo.png" },
        { team: "LAFC", MP: 34, MW: 17, MD: 9, GF: 65, GA: 40, logo: "mls/lafclogo.png" },
        { team: "Minnesota", MP: 34, MW: 16, MD: 10, GF: 56, GA: 39, logo: "mls/minnesotslogo.png" },
        { team: "Seattle", MP: 34, MW: 15, MD: 10, GF: 58, GA: 48, logo: "mls/seattlelogo.png" },
        { team: "Austin", MP: 34, MW: 13, MD: 8, GF: 37, GA: 45, logo: "mls/austinlogo.png" },
        { team: "Dallas", MP: 34, MW: 11, MD: 11, GF: 52, GA: 55, logo: "mls/dallaslogo.png" },
        { team: "Portland", MP: 34, MW: 11, MD: 11, GF: 41, GA: 48, logo: "mls/portlandlogo.png" },
        { team: "Real Salt Lake", MP: 34, MW: 12, MD: 5, GF: 38, GA: 49, logo: "mls/realsaltlakelogo.png" },
        { team: "San Jose", MP: 34, MW: 11, MD: 8, GF: 60, GA: 63, logo: "mls/sanjoselogo.png" },
        { team: "Colorado", MP: 34, MW: 11, MD: 8, GF: 40, GA: 56, logo: "mls/coloradologo.png" },
        { team: "Houston Dynamo", MP: 34, MW: 9, MD: 10, GF: 43, GA: 56, logo: "mls/houstondynamologo.png" },
        { team: "St. Louis", MP: 34, MW: 8, MD: 8, GF: 44, GA: 58, logo: "mls/stlouislogo.png" },
        { team: "LA Galaxy", MP: 34, MW: 7, MD: 9, GF: 46, GA: 66, logo: "mls/lagalaxylogo.png" },
        { team: "Sporting KC", MP: 34, MW: 7, MD: 7, GF: 46, GA: 70, logo: "mls/sportingkclogo.png" }
    ],
    fixtures: [
        ["Toronto", "San Jose"],
        ["Sporting KC", "Seattle"],
        ["Real Salt Lake", "Portland"],
        ["Inter Miami", "Orlando"],
        ["Atlanta", "Montreal"],
        ["NY Red Bulls", "Dallas"],
        ["Columbus", "Minnesota"]
    ]
},

"Argentine Liga Profesional - Group A": {
    id: "argentina-group-a",
    logo: "argentina/argentinaprimeralogo.png",
    isBasketball: false,
    teams: [
        { team: "Estudiantes", MP: 16, MW: 9, MD: 4, GF: 19, GA: 7, logo: "argentina/estudianteslogo.png" },
        { team: "Boca", MP: 16, MW: 8, MD: 6, GF: 22, GA: 9, logo: "argentina/bocalogo.png" },
        { team: "Vélez Sársfield", MP: 16, MW: 7, MD: 7, GF: 18, GA: 12, logo: "argentina/velezlogo.png" },
        { team: "Talleres", MP: 16, MW: 7, MD: 5, GF: 17, GA: 13, logo: "argentina/estudianteslogo.png" },
        { team: "Independiente", MP: 16, MW: 6, MD: 6, GF: 24, GA: 20, logo: "argentina/tellereslogo.png" },
        { team: "Lanús", MP: 16, MW: 6, MD: 6, GF: 18, GA: 15, logo: "argentina/lanuslogo.png" },
        { team: "San Lorenzo", MP: 16, MW: 5, MD: 7, GF: 14, GA: 14, logo: "argentina/sanlorenzologo.png" },
        { team: "Unión", MP: 16, MW: 5, MD: 6, GF: 24, GA: 20, logo: "argentina/unionlogo.png" },
        { team: "Instituto", MP: 16, MW: 6, MD: 3, GF: 17, GA: 17, logo: "argentina/institutologo.png" },
        { team: "Defensa", MP: 16, MW: 4, MD: 7, GF: 18, GA: 21, logo: "argentina/defensalogo.png" },
        { team: "Gimnasia Esgirma", MP: 16, MW: 5, MD: 4, GF: 14, GA: 22, logo: "argentina/gimnasiaesgrimalogo.png" },
        { team: "Platense", MP: 16, MW: 3, MD: 7, GF: 10, GA: 15, logo: "argentina/platesnselogo.png" },
        { team: "Central Córdoba", MP: 16, MW: 4, MD: 4, GF: 11, GA: 21, logo: "argentina/centralcordobalogo.png" },
        { team: "Newell's", MP: 16, MW: 3, MD: 6, GF: 15, GA: 27, logo: "argentina/newellslogo.png" },
        { team: "Deportivo Riestra", MP: 16, MW: 1, MD: 8, GF: 5, GA: 12, logo: "argentina/riestralogo.jpg" }
    ],
    fixtures: [
        ["Barracas Central", "Banfield"],
        ["Lanus", "Riestra"],
        ["Central Cordoba", "Boca Juniors"],
        ["Union", "Telleres"],
        ["San Lorenzo", "Independiente"],
        ["Platense", "Estudiantes"],
        ["Aldosivi", "Independiente Rivadavia"],
        ["Central", "Tigre"],
        ["Gimnasia LP", "Argentinos Juniors"],
        ["Racing Club", "Huracan"],
        ["Belgrano", "Sarmiento"],
        ["River Plate", "Atletico Tucuman"],
        ["Gimnasia Esgrima", "Defensa"],
        ["Velez Sarsfield", "Newells"],
        ["Estudiantes De Rio Cuarto", "Instituto"]
    ]
},

"Argentine Liga Profesional - Group B": {
    id: "argentina-group-b",
    logo: "argentina/argentinaprimeralogo.png",
    isBasketball: false,
    teams: [
        { team: "Independiente Rivadavia", MP: 16, MW: 10, MD: 4, GF: 29, GA: 15, logo: "argentina/rivadavialogo.png" },
        { team: "River Plate", MP: 16, MW: 9, MD: 2, GF: 22, GA: 12, logo: "argentina/riverplatelogo.png" },
        { team: "Argentinos Juniors", MP: 16, MW: 8, MD: 5, GF: 17, GA: 13, logo: "argentina/argentinoslogo.png" },
        { team: "Central", MP: 16, MW: 8, MD: 4, GF: 20, GA: 16, logo: "argentina/centrallogo.png" },
        { team: "Belgrano", MP: 16, MW: 7, MD: 5, GF: 17, GA: 13, logo: "argentina/belgranologo.png" },
        { team: "Gimnasia LP", MP: 16, MW: 8, MD: 2, GF: 19, GA: 19, logo: "argentina/gimnasialplogo.png" },
        { team: "Huracán", MP: 16, MW: 5, MD: 7, GF: 17, GA: 13, logo: "argentina/huracanlogo.png" },
        { team: "Racing Club", MP: 16, MW: 5, MD: 6, GF: 17, GA: 15, logo: "argentina/racingclublogo.png" },
        { team: "Barracas Central", MP: 16, MW: 5, MD: 6, GF: 15, GA: 15, logo: "argentina/barracascentrallogo.png" },
        { team: "Tigre", MP: 16, MW: 4, MD: 8, GF: 18, GA: 15, logo: "argentina/tigrelogo.png" },
        { team: "Sarmiento", MP: 16, MW: 6, MD: 1, GF: 13, GA: 20, logo: "argentina/sarmientologo.png" },
        { team: "Banfield", MP: 16, MW: 5, MD: 3, GF: 17, GA: 19, logo: "argentina/banfieldlogo.png" },
        { team: "Atlético Tucumán", MP: 16, MW: 3, MD: 5, GF: 15, GA: 20, logo: "argentina/atleticotucumanlogo.png" },
        { team: "Aldosivi", MP: 16, MW: 0, MD: 8, GF: 6, GA: 19, logo: "argentina/aldosivilogo.png" },
        { team: "Estudiantes de Río Cuarto", MP: 16, MW: 1, MD: 2, GF: 5, GA: 24, logo: "argentina/estudiantesdelriocuartologo.png" }
    ],
    fixtures: [
        ["Independiente Rivadavia", "River Plate"],
        ["Argentinos Juniors", "Central"],
        ["Belgrano", "Gimnasia LP"],
        ["Huracán", "Racing Club"],
        ["Barracas Central", "Tigre"],
        ["Sarmiento", "Banfield"],
        ["Atlético Tucumán", "Aldosivi"],
        ["Estudiantes de Río Cuarto", "Independiente Rivadavia"],
        ["River Plate", "Argentinos Juniors"],
        ["Central", "Belgrano"],
        ["Gimnasia LP", "Huracán"],
        ["Racing Club", "Barracas Central"],
        ["Tigre", "Sarmiento"],
        ["Banfield", "Atlético Tucumán"],
        ["Aldosivi", "Estudiantes de Río Cuarto"]
    ]
},

"Japanese J1 League": {
    id: "j1-league",
    logo: "japan/j1logo.png",
    isBasketball: false,
    teams: [
        { team: "Kashima Antlers", MP: 38, MW: 23, MD: 7, GF: 58, GA: 31, logo: "japan/kashimaantlerslogo.png" },
        { team: "Kashiwa", MP: 38, MW: 21, MD: 12, GF: 60, GA: 34, logo: "japan/kashiwalogo.png" },
        { team: "Kyoto", MP: 38, MW: 19, MD: 11, GF: 62, GA: 40, logo: "japan/kyotologo.png" },
        { team: "Sanfrecce", MP: 38, MW: 20, MD: 8, GF: 46, GA: 28, logo: "japan/sanfreecelogo.png" },
        { team: "Vissel Kobe", MP: 38, MW: 18, MD: 10, GF: 46, GA: 33, logo: "japan/visselkobelogo.png" },
        { team: "Machida", MP: 38, MW: 17, MD: 9, GF: 52, GA: 38, logo: "japan/machidalogo.png" },
        { team: "Urawa Reds", MP: 38, MW: 16, MD: 11, GF: 45, GA: 39, logo: "japan/urawaredslogo.png" },
        { team: "Kawasaki", MP: 38, MW: 15, MD: 12, GF: 67, GA: 57, logo: "japan/kawasakilogo.png" },
        { team: "Gamba Osaka", MP: 38, MW: 17, MD: 6, GF: 53, GA: 55, logo: "japan/gambaosakalogo.png" },
        { team: "Cerezo Osaka", MP: 38, MW: 14, MD: 10, GF: 60, GA: 57, logo: "japan/cerezoosakalogo.png" },
        { team: "FC Tokyo", MP: 38, MW: 13, MD: 11, GF: 41, GA: 48, logo: "japan/fctokyologo.png" },
        { team: "Avispa", MP: 38, MW: 12, MD: 12, GF: 34, GA: 38, logo: "japan/avispalogo.png" },
        { team: "Okayama", MP: 38, MW: 12, MD: 9, GF: 34, GA: 43, logo: "japan/okayamalogo.png" },
        { team: "Shimizu", MP: 38, MW: 11, MD: 11, GF: 41, GA: 51, logo: "japan/shimizulogo.png" },
        { team: "Yokohama FM", MP: 38, MW: 12, MD: 7, GF: 46, GA: 47, logo: "japan/yokohamafmlogo.png" },
        { team: "Nagoya", MP: 38, MW: 11, MD: 10, GF: 44, GA: 56, logo: "japan/nagoyalogo.png" },
        { team: "Tokyo Verdy", MP: 38, MW: 11, MD: 10, GF: 23, GA: 41, logo: "japan/nagoyalogo.png" },
        { team: "Yokohama FC", MP: 38, MW: 9, MD: 8, GF: 27, GA: 45, logo: "japan/yokogamafclogo.png" },
        { team: "Shonan", MP: 38, MW: 8, MD: 8, GF: 36, GA: 63, logo: "japan/shonanlogo.png" },
        { team: "Niigata", MP: 38, MW: 4, MD: 12, GF: 36, GA: 67, logo: "japan/niigatalogologo.png" }
    ],
    fixtures: [
        ["Okayama", "Sanfrecce"],
        ["Kyoto", "Shimizu"],
        ["Yokohama FM", "Mito"],
        ["Tokyo", "Kawasaki"],
        ["Gamba Osaka", "Vissel Kobe"],
        ["Urawa Reds", "JEF"],
        ["Tokyo Verdy", "Kashiwa"],
        ["Cerezo Osaka", "Avispa Osaka"],
        ["Kashima Antlers", "Machida"],
        ["Nagasaki", "Nagoya"]
    ]
},

"Japanese J2 League": {
    id: "j2-league",
    logo: "japan/j2logo.png",
    isBasketball: false,
    teams: [
        { team: "Mito HollyHock", MP: 38, MW: 20, MD: 10, GF: 55, GA: 34, logo: "japan/mitologo.png" },
        { team: "V-Varen Nagasaki", MP: 38, MW: 19, MD: 13, GF: 63, GA: 44, logo: "japan/nagasaki.png" },
        { team: "JEF United", MP: 38, MW: 20, MD: 9, GF: 56, GA: 34, logo: "japan/jeflogo.png" },
        { team: "Tokushima Vortis", MP: 38, MW: 18, MD: 11, GF: 45, GA: 24, logo: "japan/tokushimavortislogo.png" },
        { team: "Júbilo Iwata", MP: 38, MW: 19, MD: 7, GF: 59, GA: 51, logo: "japan/jubiloiwatalogo.png" },
        { team: "Omiya Ardija", MP: 38, MW: 18, MD: 9, GF: 60, GA: 39, logo: "japan/omiyalogo.png" },
        { team: "Vegalta Sendai", MP: 38, MW: 16, MD: 14, GF: 47, GA: 36, logo: "japan/velgatalogo.png" },
        { team: "Sagan Tosu", MP: 38, MW: 16, MD: 10, GF: 46, GA: 43, logo: "japan/sagantosulogo.png" },
        { team: "Iwaki FC", MP: 38, MW: 15, MD: 11, GF: 55, GA: 44, logo: "japan/iwakilogo.png" },
        { team: "Montedio Yamagata", MP: 38, MW: 15, MD: 8, GF: 58, GA: 54, logo: "japan/yamagatalogo.png" },
        { team: "Imabari", MP: 38, MW: 13, MD: 14, GF: 46, GA: 46, logo: "japan/imabarilogo.png" },
        { team: "Consadole Sapporo", MP: 38, MW: 16, MD: 5, GF: 50, GA: 63, logo: "japan/consadolelogo.png" },
        { team: "Ventforet Kofu", MP: 38, MW: 11, MD: 11, GF: 37, GA: 45, logo: "japan/ventforetlogo.png" },
        { team: "Blaublitz", MP: 38, MW: 11, MD: 10, GF: 43, GA: 59, logo: "japan/blaublitzlogo.png" },
        { team: "Fujieda MYFC", MP: 38, MW: 9, MD: 12, GF: 41, GA: 50, logo: "japan/fujieda.png" },
        { team: "Oita Trinita", MP: 38, MW: 8, MD: 14, GF: 27, GA: 44, logo: "japan/oitalogo.png" },
        { team: "Kataller Toyama", MP: 38, MW: 9, MD: 10, GF: 34, GA: 49, logo: "japan/toyamalogo.png" },
        { team: "Roasso Kumamoto", MP: 38, MW: 9, MD: 10, GF: 41, GA: 57, logo: "japan/roassologo.png" },
        { team: "Renofa Yamaguchi", MP: 38, MW: 7, MD: 15, GF: 36, GA: 47, logo: "japan/renofalogo.png" },
        { team: "Ehime FC", MP: 38, MW: 3, MD: 13, GF: 35, GA: 71, logo: "japan/ehimelogo.png" }
    ],
    fixtures: [
        ["Consadole Sapporo", "Jubilo Iwata"],
        ["Fujieda MYFC", "Iwaki FC"],
        ["Renofa Yamaguchi", "Roasso Kumamoto"],
        ["F.C. Gifu", "Omiya Ardija"],
        ["Vegalta Sendai", "Yokohama FC"],
        ["Nara Club", "Kataller Toyama"],
        ["Niigata", "Ehime FC"],
        ["Sagan Tosu", "Ryukyu"],
        ["Gunma", "Sagamihara"],
        ["Nagano", "Ventforet Kofu"],
        ["Vanraure Hachinohe", "Tochigi SC"],
        ["Tegevajaro Miyazaki", "Reilac Shiga"],
        ["Tokushima Vortis", "Imabari"],
        ["Kitayushu", "Kagoshima United"],
        ["Matsumoto Yamaga", "Fukushima United"],
        ["Kamatamare Sanuki", "Osaka"],
        ["Montedio Yamagata", "Shonan Bellmare"],
        ["Tottori", "Oita Trinita"],
        ["Blaublitz Tochigi FC", "Kanazawa"],
        ["Ehime FC", "Mito HollyHock"]
    ]
},

    "NBA": {
        id: "nba",
        logo: "nba.png",
        isBasketball: true,
        teams: [
            { team: "LA Lakers", MP: 82, MW: 52, GF: 118, GA: 112 },
            { team: "Boston Celtics", MP: 82, MW: 64, GF: 120, GA: 109 },
            { team: "Denver Nuggets", MP: 82, MW: 57, GF: 115, GA: 110 },
            { team: "Milwaukee Bucks", MP: 82, MW: 49, GF: 119, GA: 117 },
            { team: "Philadelphia 76ers", MP: 82, MW: 54, GF: 117, GA: 111 },
            { team: "Phoenix Suns", MP: 82, MW: 45, GF: 115, GA: 113 },
            { team: "Golden State Warriors", MP: 82, MW: 46, GF: 118, GA: 117 },
            { team: "Miami Heat", MP: 82, MW: 44, GF: 110, GA: 109 },
            { team: "New York Knicks", MP: 82, MW: 47, GF: 115, GA: 112 },
            { team: "Dallas Mavericks", MP: 82, MW: 50, GF: 118, GA: 116 }
        ],
        fixtures: [
            ["LA Lakers", "Boston Celtics"],
            ["Denver Nuggets", "Milwaukee Bucks"],
            ["Philadelphia 76ers", "Phoenix Suns"],
            ["Golden State Warriors", "Miami Heat"],
            ["New York Knicks", "Dallas Mavericks"]
        ]
    },

    "EuroLeague": {
        id: "euroleague",
        logo: "euroleague.png",
        isBasketball: true,
        teams: [
            { team: "Real Madrid", MP: 34, MW: 27, GF: 88, GA: 79 },
            { team: "Panathinaikos", MP: 34, MW: 23, GF: 84, GA: 78 },
            { team: "Monaco", MP: 34, MW: 21, GF: 86, GA: 82 },
            { team: "Fenerbahce", MP: 34, MW: 20, GF: 83, GA: 81 },
            { team: "Olympiacos", MP: 34, MW: 22, GF: 85, GA: 80 },
            { team: "Barcelona", MP: 34, MW: 22, GF: 87, GA: 82 },
            { team: "Maccabi Tel Aviv", MP: 34, MW: 20, GF: 84, GA: 83 },
            { team: "Partizan", MP: 34, MW: 19, GF: 82, GA: 81 },
            { team: "Anadolu Efes", MP: 34, MW: 17, GF: 82, GA: 84 },
            { team: "Virtus Bologna", MP: 34, MW: 17, GF: 81, GA: 83 },
            { team: "Valencia", MP: 34, MW: 16, GF: 80, GA: 82 },
            { team: "Bayern Munich", MP: 34, MW: 15, GF: 79, GA: 83 },
            { team: "Crvena Zvezda", MP: 34, MW: 14, GF: 78, GA: 84 },
            { team: "ASVEL", MP: 34, MW: 12, GF: 77, GA: 86 },
            { team: "ALBA Berlin", MP: 34, MW: 9, GF: 75, GA: 89 },
            { team: "Baskonia", MP: 34, MW: 15, GF: 79, GA: 81 },
            { team: "Olimpia Milano", MP: 34, MW: 14, GF: 78, GA: 82 },
            { team: "Zalgiris Kaunas", MP: 34, MW: 18, GF: 80, GA: 79 }
        ],
        fixtures: [
            ["Valencia", "Barcelona"],
            ["Real Madrid", "Fenerbahce"],
            ["Olympiacos", "Barcelona"],
            ["Maccabi Tel Aviv", "Partizan"],
            ["Anadolu Efes", "Virtus Bologna"]
        ]
    }
};

console.log("✅ Data loaded successfully!", Object.keys(leaguesData).length, "leagues");