// ==================== COMPLETE MATCH RESULTS DATA ====================

const matchesData = {
/*
    "English Premier League": [
        { home: "Manchester United", away: "Crystal Palace", home_score: 2, away_score: 1 },
        { home: "Brighton", away: "Nottingham", home_score: 1, away_score: 1 },
        { home: "Fulham", away: "Tottenham", home_score: 2, away_score: 1 },
        { home: "Arsenal", away: "Chelsea", home_score: 2, away_score: 1 },
        { home: "Bournemouth", away: "Brentford", home_score: 0, away_score: 0 },
        { home: "Everton", away: "Burnley", home_score: 2, away_score: 0 },
        { home: "Leeds", away: "Sunderland", home_score: 0, away_score: 1 },
        { home: "Wolves", away: "Liverpool", home_score: 2, away_score: 1 },
        { home: "Brighton", away: "Arsenal", home_score: 0, away_score: 1 },
        { home: "Fulham", away: "West Ham", home_score: 0, away_score: 1 },
        { home: "Manchester City", away: "Nottingham", home_score: 2, away_score: 2 },
        { home: "Aston Villa", away: "Chelsea", home_score: 1, away_score: 4 },
        { home: "Newcastle", away: "Manchester United", home_score: 2, away_score: 1 },
        { home: "Tottenham", away: "Crystal Palace", home_score: 1, away_score: 3 },
        { home: "Sunderland", away: "Brighton", home_score: 0, away_score: 1 },
        { home: "Burnley", away: "Bournemouth", home_score: 0, away_score: 0 },
        { home: "Chelsea", away: "Newcastle", home_score: 0, away_score: 1 },
        { home: "Arsenal", away: "Everton", home_score: 2, away_score: 0 },
        { home: "West Ham", away: "Manchester City", home_score: 1, away_score: 1 },
        { home: "Nottingham", away: "Fulham", home_score: 0, away_score: 0 },
        { home: "Manchester United", away: "Aston Villa", home_score: 3, away_score: 1 },
        { home: "Crystal Palace", away: "Leeds", home_score: 0, away_score: 0 },
        { home: "Liverpool", away: "Tottenham", home_score: 1, away_score: 1 },
        { home: "Brentford", away: "Wolves", home_score: 2, away_score: 2 },
        { home: "Bournemouth", away: "Manchester United", home_score: 2, away_score: 2 },
        { home: "Brighton", away: "Liverpool", home_score: 2, away_score: 1 },
        { home: "Fulham", away: "Burnley", home_score: 3, away_score: 1 },
        { home: "Everton", away: "Chelsea", home_score: 3, away_score: 0 },
        { home: "Leeds", away: "Brentford", home_score: 0, away_score: 0 },
        { home: "Newcastle", away: "Sunderland", home_score: 1, away_score: 2 },
        { home: "Aston Villa", away: "West Ham", home_score: 2, away_score: 0 },
        { home: "Tottenham", away: "Nottingham", home_score: 0, away_score: 3 },
        { home: "West Ham", away: "Wolves", home_score: 4, away_score: 0 },
        { home: "Arsenal", away: "Bournemouth", home_score: 1, away_score: 2 },
        { home: "Brentford", away: "Everton", home_score: 2, away_score: 2 },
        { home: "Burnley", away: "Brighton", home_score: 0, away_score: 2 },
        { home: "Liverpool", away: "Fulham", home_score: 2, away_score: 0 },
        { home: "Crystal Palace", away: "Newcastle", home_score: 2, away_score: 1 },
        { home: "Sunderland", away: "Tottenham", home_score: 1, away_score: 0 },
        { home: "Nottingham", away: "Aston Villa", home_score: 1, away_score: 1 },
        { home: "Chelsea", away: "Manchester City", home_score: 0, away_score: 3 },
        { home: "Manchester United", away: "Leeds", home_score: 1, away_score: 2 },
        { home: "Brentford", away: "Fulham", home_score: 0, away_score: 0 },
        { home: "Leeds", away: "Wolves", home_score: 3, away_score: 0 },
        { home: "Newcastle", away: "Bournemouth", home_score: 1, away_score: 2 },
        { home: "Chelsea", away: "Manchester United", home_score: 0, away_score: 1 },
        { home: "Nottingham", away: "Burnley", home_score: 0, away_score: 1 },
        { home: "Aston Villa", away: "Sunderland", home_score: 4, away_score: 3 },
        { home: "Everton", away: "Liverpool", home_score: 1, away_score: 2 },
        { home: "Manchester City", away: "Arsenal", home_score: 2, away_score: 1 },
        { home: "Crystal Palace", away: "West Ham", home_score: 0, away_score: 0 },
        { home: "Brighton", away: "Chelsea", home_score: 3, away_score: 0 },
        { home: "Burnley", away: "Manchester City", home_score: 0, away_score: 1 },
        { home: "Bournemouth", away: "Leeds", home_score: 2, away_score: 2 },
        { home: "Sunderland", away: "Nottingham", home_score: 0, away_score: 5 },
        { home: "Fulham", away: "Aston Villa", home_score: 1, away_score: 0 },
        { home: "West Ham", away: "Everton", home_score: 3, away_score: 0 },
        { home: "Wolves", away: "Tottenham", home_score: 0, away_score: 1 },
        { home: "Liverpool", away: "Crystal Palace", home_score: 3, away_score: 1 },
        { home: "Arsenal", away: "Newcastle", home_score: 1, away_score: 0 },
        { home: "Manchester United", away: "Brentford", home_score: 2, away_score: 1 },
        { home: "Leeds", away: "Burnley", home_score: 3, away_score: 1 },
        { home: "Brentford", away: "West Ham", home_score: 3, away_score: 0 },
        { home: "Wolves", away: "Sunderland", home_score: 1, away_score: 1 },
        { home: "Newcastle", away: "Brighton", home_score: 3, away_score: 1 },
        { home: "Arsenal", away: "Fulham", home_score: 3, away_score: 0 },
        { home: "Bournemouth", away: "Crystal Palace", home_score: 3, away_score: 0 },
        { home: "Manchester United", away: "Liverpool", home_score: 3, away_score: 2 },
        { home: "Aston Villa", away: "Tottenham", home_score: 1, away_score: 2 },
        { home: "Chelsea", away: "Nottingham", home_score: 1, away_score: 3 }
    ],

    "Spanish La Liga": [
        { home: "Osasuna", away: "Mallorca", home_score: 2, away_score: 2 },
        { home: "Levante", away: "Girona", home_score: 1, away_score: 1 },
        { home: "Atletico Madrid", away: "Real Sociedad", home_score: 3, away_score: 2 },
        { home: "Athletic Club", away: "Barcelona", home_score: 0, away_score: 1 },
        { home: "Villarreal", away: "Elche", home_score: 2, away_score: 1 },
        { home: "Getafe", away: "Real Betis", home_score: 0, away_score: 2 },
        { home: "Sevilla", away: "Rayo Vallecano", home_score: 1, away_score: 1 },
        { home: "Valencia", away: "Alaves", home_score: 3, away_score: 2 },
        { home: "Espanyol", away: "Oviedo", home_score: 1, away_score: 1 },
        { home: "Alaves", away: "Villarreal", home_score: 1, away_score: 1 },
        { home: "Girona", away: "Athletic Bilbao", home_score: 3, away_score: 0 },
        { home: "Athletic Club", away: "Getafe", home_score: 1, away_score: 0 },
        { home: "Oviedo", away: "Valencia", home_score: 1, away_score: 0 },
        { home: "Real Madrid", away: "Elche", home_score: 4, away_score: 1 },
        { home: "Mallorca", away: "Espanyol", home_score: 2, away_score: 1 },
        { home: "Barcelona", away: "Sevilla", home_score: 5, away_score: 2 },
        { home: "Real Betis", away: "Celta Vigo", home_score: 1, away_score: 1 },
        { home: "Real Sociedad", away: "Osasuna", home_score: 1, away_score: 2 },
        { home: "Rayo Vallecano", away: "Levante", home_score: 1, away_score: 1 },
        { home: "Villarreal", away: "Real Sociedad", home_score: 3, away_score: 1 },
        { home: "Elche", away: "Mallorca", home_score: 2, away_score: 1 },
        { home: "Espanyol", away: "Getafe", home_score: 1, away_score: 2 },
        { home: "Osasuna", away: "Girona", home_score: 1, away_score: 0 },
        { home: "Levante", away: "Oviedo", home_score: 4, away_score: 2 },
        { home: "Sevilla", away: "Valencia", home_score: 0, away_score: 2 },
        { home: "Barcelona", away: "Rayo Vallecano", home_score: 1, away_score: 0 },
        { home: "Celta Vigo", away: "Alaves", home_score: 3, away_score: 4 },
        { home: "Athletic Bilbao", away: "Real Betis", home_score: 2, away_score: 0 },
        { home: "Real Madrid", away: "Atletico Madrid", home_score: 3, away_score: 2 },
        { home: "Rayo Vallecano", away: "Elche", home_score: 1, away_score: 0 },
        { home: "Real Sociedad", away: "Levante", home_score: 2, away_score: 0 },
        { home: "Mallorca", away: "Real Madrid", home_score: 2, away_score: 1 },
        { home: "Real Betis", away: "Espanyol", home_score: 0, away_score: 0 },
        { home: "Atletico Madrid", away: "Barcelona", home_score: 1, away_score: 2 },
        { home: "Getafe", away: "Athletic Club", home_score: 2, away_score: 0 },
        { home: "Valencia", away: "Celta Vigo", home_score: 2, away_score: 3 },
        { home: "Oviedo", away: "Sevilla", home_score: 1, away_score: 0 },
        { home: "Alaves", away: "Osasuna", home_score: 2, away_score: 2 },
        { home: "Girona", away: "Villarreal", home_score: 1, away_score: 1 }
    ],

    "Italian Serie A": [
        { home: "Sassuolo", away: "Verona", home_score: 3, away_score: 0 },
        { home: "Juventus", away: "Como", home_score: 0, away_score: 2 },
        { home: "Leece", away: "Inter", home_score: 0, away_score: 2 },
        { home: "Cagliari", away: "Lazio", home_score: 0, away_score: 0 },
        { home: "Genoa", away: "Torino", home_score: 3, away_score: 0 },
        { home: "Atalanta", away: "Napoli", home_score: 2, away_score: 1 },
        { home: "Milan", away: "Parma", home_score: 0, away_score: 1 },
        { home: "Roma", away: "Cremonese", home_score: 3, away_score: 0 },
        { home: "Fiorentina", away: "Pisa", home_score: 1, away_score: 0 },
        { home: "Bologna", away: "Udinese", home_score: 1, away_score: 0 },
        { home: "Parma", away: "Cagliari", home_score: 1, away_score: 1 },
        { home: "Como", away: "Leece", home_score: 3, away_score: 1 },
        { home: "Verona", away: "Napoli", home_score: 1, away_score: 2 },
        { home: "Inter", away: "Genoa", home_score: 2, away_score: 0 },
        { home: "Cremonese", away: "Milan", home_score: 0, away_score: 2 },
        { home: "Sassuolo", away: "Atalanta", home_score: 2, away_score: 1 },
        { home: "Torino", away: "Lazio", home_score: 2, away_score: 0 },
        { home: "Roma", away: "Juventus", home_score: 3, away_score: 3 },
        { home: "Pisa", away: "Bologna", home_score: 0, away_score: 1 },
        { home: "Udinese", away: "Fiorentina", home_score: 3, away_score: 0 },
        { home: "Napoli", away: "Torino", home_score: 2, away_score: 1 },
        { home: "Cagliari", away: "Como", home_score: 1, away_score: 2 },
        { home: "Atalanta", away: "Udinese", home_score: 2, away_score: 2 },
        { home: "Juventus", away: "Pisa", home_score: 4, away_score: 0 },
        { home: "Leece", away: "Cremonese", home_score: 2, away_score: 1 },
        { home: "Bologna", away: "Verona", home_score: 1, away_score: 2 },
        { home: "Fiorentina", away: "Parma", home_score: 0, away_score: 0 },
        { home: "Genoa", away: "Roma", home_score: 2, away_score: 1 },
        { home: "Milan", away: "Inter", home_score: 1, away_score: 0 },
        { home: "Lazio", away: "Sassuolo", home_score: 2, away_score: 1 },
        { home: "Torino", away: "Parma", home_score: 4, away_score: 1 },
        { home: "Inter", away: "Atalanta", home_score: 1, away_score: 1 },
        { home: "Napoli", away: "Leece", home_score: 2, away_score: 1 },
        { home: "Udinese", away: "Juventus", home_score: 0, away_score: 1 },
        { home: "Verona", away: "Genoa", home_score: 0, away_score: 2 },
        { home: "Pisa", away: "Cagliari", home_score: 3, away_score: 1 },
        { home: "Sassuolo", away: "Bologna", home_score: 3, away_score: 1 },
        { home: "Como", away: "Roma", home_score: 2, away_score: 1 },
        { home: "Lazio", away: "Milan", home_score: 1, away_score: 0 },
        { home: "Cremonese", away: "Fiorentina", home_score: 1, away_score: 4 },
        { home: "Cagliari", away: "Napoli", home_score: 0, away_score: 1 },
        { home: "Genoa", away: "Udinese", home_score: 0, away_score: 2 },
        { home: "Parma", away: "Cremonese", home_score: 0, away_score: 2 },
        { home: "Milan", away: "Torino", home_score: 3, away_score: 2 },
        { home: "Juventus", away: "Sassuolo", home_score: 1, away_score: 1 },
        { home: "Como", away: "Pisa", home_score: 5, away_score: 0 },
        { home: "Atalanta", away: "Verona", home_score: 1, away_score: 0 },
        { home: "Bologna", away: "Lazio", home_score: 0, away_score: 2 },
        { home: "Roma", away: "Leece", home_score: 1, away_score: 0 },
        { home: "Fiorentina", away: "Inter", home_score: 1, away_score: 1 },
        { home: "Sassuolo", away: "Cagliari", home_score: 2, away_score: 1 },
        { home: "Verona", away: "Fiorentina", home_score: 0, away_score: 1 },
        { home: "Lazio", away: "Parma", home_score: 1, away_score: 1 },
        { home: "Pisa", away: "Torino", home_score: 1, away_score: 1 },
        { home: "Inter", away: "Roma", home_score: 5, away_score: 2 },
        { home: "Udinese", away: "Como", home_score: 0, away_score: 0 },
        { home: "Leece", away: "Atalanta", home_score: 0, away_score: 3 },
        { home: "Juventus", away: "Genoa", home_score: 2, away_score: 0 },
        { home: "Napoli", away: "Milan", home_score: 1, away_score: 0 },
        { home: "Roma", away: "Pisa", home_score: 3, away_score: 0 },
        { home: "Torino", away: "Verona", home_score: 2, away_score: 1 },
        { home: "Cagliari", away: "Cremonese", home_score: 1, away_score: 0 },
        { home: "Milan", away: "Udinese", home_score: 0, away_score: 3 },
        { home: "Atalanta", away: "Juventus", home_score: 0, away_score: 1 },
        { home: "Genoa", away: "Sassuolo", home_score: 2, away_score: 1 },
        { home: "Parma", away: "Napoli", home_score: 1, away_score: 1 },
        { home: "Bologna", away: "Leece", home_score: 2, away_score: 0 },
        { home: "Como", away: "Inter", home_score: 3, away_score: 4 },
        { home: "Fiorentina", away: "Lazio", home_score: 1, away_score: 0 }
    ],

    "French Ligue 1": [
        { home: "Strasbourg", away: "Lens", home_score: 1, away_score: 1 },
        { home: "Rennes", away: "Toulouse", home_score: 1, away_score: 0 },
        { home: "Monaco", away: "Angers", home_score: 2, away_score: 0 },
        { home: "Le Havre", away: "PSG", home_score: 0, away_score: 1 },
        { home: "Paris", away: "Nice", home_score: 1, away_score: 0 },
        { home: "Lorient", away: "Auxerre", home_score: 2, away_score: 2 },
        { home: "Lille", away: "Nantes", home_score: 1, away_score: 0 },
        { home: "Metz", away: "Brest", home_score: 0, away_score: 1 },
        { home: "Marseille", away: "Lyon", home_score: 3, away_score: 2 },
        { home: "PSG", away: "Monaco", home_score: 1, away_score: 3 },
        { home: "Nantes", away: "Angers", home_score: 0, away_score: 1 },
        { home: "Auxerre", away: "Strasbourg", home_score: 0, away_score: 0 },
        { home: "Toulouse", away: "Marseille", home_score: 0, away_score: 1 },
        { home: "Lens", away: "Metz", home_score: 3, away_score: 0 },
        { home: "Lille", away: "Lorient", home_score: 1, away_score: 1 },
        { home: "Brest", away: "Le Havre", home_score: 2, away_score: 0 },
        { home: "Nice", away: "Rennes", home_score: 0, away_score: 4 },
        { home: "Lyon", away: "Paris", home_score: 1, away_score: 1 },
        { home: "Marseille", away: "Auxerre", home_score: 1, away_score: 0 },
        { home: "Lorient", away: "Lens", home_score: 2, away_score: 1 },
        { home: "Monaco", away: "Brest", home_score: 2, away_score: 0 },
        { home: "Strasbourg", away: "Paris", home_score: 0, away_score: 0 },
        { home: "Metz", away: "Toulouse", home_score: 3, away_score: 4 },
        { home: "Le Havre", away: "Lyon", home_score: 0, away_score: 0 },
        { home: "Rennes", away: "Lille", home_score: 1, away_score: 2 },
        { home: "Angers", away: "Brest", home_score: 5, away_score: 1 },
        { home: "Toulouse", away: "Lorient", home_score: 1, away_score: 0 },
        { home: "Auxerre", away: "Brest", home_score: 3, away_score: 0 },
        { home: "Nice", away: "PSG", home_score: 0, away_score: 4 },
        { home: "Lyon", away: "Monaco", home_score: 1, away_score: 2 },
        { home: "Rennes", away: "Metz", home_score: 0, away_score: 0 },
        { home: "Paris", away: "Le Havre", home_score: 3, away_score: 2 },
        { home: "Marseille", away: "Lille", home_score: 1, away_score: 2 },
        { home: "Nantes", away: "Strasbourg", home_score: 2, away_score: 3 },
        { home: "PSG", away: "Toulouse", home_score: 3, away_score: 1 },
        { home: "Strasbourg", away: "Nice", home_score: 3, away_score: 1 },
        { home: "Brest", away: "Rennes", home_score: 3, away_score: 4 },
        { home: "Lille", away: "Lens", home_score: 3, away_score: 0 },
        { home: "Angers", away: "Lyon", home_score: 0, away_score: 0 },
        { home: "Metz", away: "Nantes", home_score: 0, away_score: 0 },
        { home: "Lorient", away: "Paris", home_score: 1, away_score: 1 },
        { home: "Le Havre", away: "Auxerre", home_score: 1, away_score: 1 },
        { home: "Monaco", away: "Marseille", home_score: 2, away_score: 1 },
        { home: "Paris", away: "Monaco", home_score: 4, away_score: 1 }
    ],

    "German Bundesliga": [
        { home: "Stuttgart", away: "Wolfsburg", home_score: 4, away_score: 0 },
        { home: "Frankfurt", away: "Freiburg", home_score: 2, away_score: 0 },
        { home: "Hamburger", away: "Leipzig", home_score: 1, away_score: 2 },
        { home: "Hamburger", away: "Leverkusen", home_score: 0, away_score: 1 },
        { home: "Bayern", away: "Monchengladbach", home_score: 4, away_score: 1 },
        { home: "Leipzig", away: "Augsburg", home_score: 2, away_score: 1 },
        { home: "Wolfsburg", away: "Hamburger", home_score: 1, away_score: 2 },
        { home: "Freiburg", away: "Leverkusen", home_score: 3, away_score: 3 },
        { home: "Heidenheim", away: "Hoffenheim", home_score: 2, away_score: 4 },
        { home: "Koln", away: "Dortmund", home_score: 1, away_score: 2 },
        { home: "St. Pauli", away: "Frankfurt", home_score: 0, away_score: 0 },
        { home: "Union Berlin", away: "Werder", home_score: 1, away_score: 4 },
        { home: "Monchengladbach", away: "St. Pauli", home_score: 2, away_score: 0 },
        { home: "Frankfurt", away: "Heidenheim", home_score: 1, away_score: 0 },
        { home: "Dortmund", away: "Augsburg", home_score: 2, away_score: 0 },
        { home: "Leverkusen", away: "Bayern", home_score: 1, away_score: 1 },
        { home: "Hoffenheim", away: "Wolfsburg", home_score: 1, away_score: 1 },
        { home: "St. Hamburger", away: "Koln", home_score: 1, away_score: 1 },
        { home: "Werder", away: "Mainz", home_score: 0, away_score: 2 },
        { home: "Freiburg", away: "Union Berlin", home_score: 0, away_score: 1 },
        { home: "Stuttgart", away: "Leipzig", home_score: 1, away_score: 0 },
        { home: "Leipzig", away: "Hoffenheim", home_score: 5, away_score: 0 },
        { home: "Wolfsburg", away: "Werder", home_score: 0, away_score: 1 },
        { home: "Koln", away: "Monchengladbach", home_score: 3, away_score: 3 },
        { home: "Dortmund", away: "Hamburger", home_score: 3, away_score: 2 },
        { home: "Mainz", away: "Frankfurt", home_score: 2, away_score: 1 },
        { home: "St. Pauli", away: "Freiburg", home_score: 1, away_score: 2 },
        { home: "Augsburg", away: "Stuttgart", home_score: 2, away_score: 5 },
        { home: "Freiburg", away: "Bayern", home_score: 2, away_score: 3 },
        { home: "Hoffenheim", away: "Mainz", home_score: 1, away_score: 2 },
        { home: "Werder", away: "Leipzig", home_score: 1, away_score: 2 },
        { home: "Hamburger", away: "Augsburg", home_score: 1, away_score: 1 },
        { home: "Monchengladbach", away: "Heidenheim", home_score: 2, away_score: 2 },
        { home: "Leverkusen", away: "Wolfsburg", home_score: 6, away_score: 3 },
        { home: "Stuttgart", away: "Dortmund", home_score: 0, away_score: 2 },
        { home: "Union Berlin", away: "St. Pauli", home_score: 1, away_score: 1 },
        { home: "Frankfurt", away: "Koln", home_score: 2, away_score: 2 },
        { home: "Augsburg", away: "Hoffenheim", home_score: 2, away_score: 2 }
    ],
*/
    "Chilean Primera División": [
        { home: "Palestino", away: "La Serena", home_score: 5, away_score: 1 },
        { home: "Coquimbo", away: "Audax Italiano", home_score: 3, away_score: 0 },
        { home: "O'Higgins", away: "Universidad de Concepción", home_score: 0, away_score: 1 },
        { home: "Deportes Limache", away: "Universidad Católica", home_score: 0, away_score: 2 },
        { home: "Huachipato", away: "Unión La Calera", home_score: 3, away_score: 1 },
        { home: "Cobresal", away: "Universidad de Chile", home_score: 1, away_score: 0 },
        { home: "Colo-Colo", away: "Ñublense", home_score: 6, away_score: 2 },
        { home: "Concepción", away: "Everton", home_score: 0, away_score: 2 },
        { home: "Everton", away: "Coquimbo", home_score: 1, away_score: 1 },
        { home: "Audax Italiano", away: "Cobresal", home_score: 2, away_score: 1 },
        { home: "Ñublense", away: "Universidad de Concepción", home_score: 2, away_score: 2 },
        { home: "Unión La Calera", away: "Palestino", home_score: 1, away_score: 2 },
        { home: "Concepción", away: "Huachipato", home_score: 2, away_score: 0 },
        { home: "La Serena", away: "Deportes Limache", home_score: 4, away_score: 1 },
        { home: "Universidad Católica", away: "Colo-Colo", home_score: 1, away_score: 2 },
        { home: "Cobresal", away: "Ñublense", home_score: 0, away_score: 1 },
        { home: "Universidad de Concepción", away: "Unión La Calera", home_score: 0, away_score: 0 },
        { home: "La Serena", away: "Colo-Colo", home_score: 2, away_score: 4 },
        { home: "Universidad de Concepción", away: "Concepción", home_score: 2, away_score: 1 },
        { home: "Deportes Limache", away: "Coquimbo", home_score: 2, away_score: 3 },
        { home: "Huachipato", away: "Universidad Católica", home_score: 0, away_score: 3 },
        { home: "O'Higgins", away: "Everton", home_score: 2, away_score: 3 },
        { home: "Palestino", away: "Audax Italiano", home_score: 0, away_score: 0 }
    ],

    "Japanese J1 League": [
        { home: "JEF", away: "Kashiwa", home_score: 2, away_score: 1 },
        { home: "FC Tokyo", away: "Yokohama FM", home_score: 3, away_score: 0 },
        { home: "Urawa Reds", away: "Mito", home_score: 2, away_score: 0 },
        { home: "Kashima Antlers", away: "Tokyo Verdy", home_score: 2, away_score: 0 },
        { home: "Avispa", away: "Nagoya", home_score: 1, away_score: 5 },
        { home: "Okayama", away: "Kyoto", home_score: 1, away_score: 0 },
        { home: "Gamba Osaka", away: "Nagasaki", home_score: 3, away_score: 2 },
        { home: "Yokohama FM", away: "JEF", home_score: 2, away_score: 0 },
        { home: "Kyoto", away: "Cerezo Osaka", home_score: 1, away_score: 2 },
        { home: "Shimizu", away: "Okayama", home_score: 1, away_score: 1 },
        { home: "Kashiwa", away: "Machida", home_score: 0, away_score: 1 },
        { home: "Nagoya", away: "Vissel Kobe", home_score: 0, away_score: 3 },
        { home: "Mito", away: "FC Tokyo", home_score: 1, away_score: 1 },
        { home: "Kashima Antlers", away: "Kawasaki", home_score: 1, away_score: 0 },
        { home: "Nagasaki", away: "Avispa", home_score: 1, away_score: 0 },
        { home: "Cerezo Osaka", away: "Okayama", home_score: 1, away_score: 2 },
        { home: "Vissel Kobe", away: "Gamba Osaka", home_score: 2, away_score: 2 },
        { home: "Mito", away: "Yokohama FM", home_score: 1, away_score: 0 },
        { home: "Avispa", away: "Shimizu", home_score: 1, away_score: 1 },
        { home: "Nagoya", away: "Sanfreece", home_score: 2, away_score: 1 },
        { home: "JEF", away: "FC Tokyo", home_score: 1, away_score: 2 },
        { home: "Nagasaki", away: "Kyoto", home_score: 1, away_score: 2 },
        { home: "Tokyo Verdy", away: "Kawasaki", home_score: 0, away_score: 2 },
        { home: "Machida", away: "Kashima Antlers", home_score: 0, away_score: 3 },
        { home: "Urawa Reds", away: "Kashiwa", home_score: 1, away_score: 1 },
        { home: "Okayama", away: "Nagasaki", home_score: 0, away_score: 1 },
        { home: "Avispa", away: "Gamba Osaka", home_score: 2, away_score: 2 },
        { home: "Shimizu", away: "Sanfreece", home_score: 3, away_score: 1 },
        { home: "Kyoto", away: "Nagoya", home_score: 1, away_score: 1 },
        { home: "Tokyo Verdy", away: "FC Tokyo", home_score: 0, away_score: 0 },
        { home: "Cerezo Osaka", away: "Vissel Kobe", home_score: 1, away_score: 1 },
        { home: "Kashima Antlers", away: "JEF", home_score: 2, away_score: 1 },
        { home: "Kawasaki", away: "Yokohama FM", home_score: 0, away_score: 5 },
        { home: "Kashiwa", away: "Mito", home_score: 3, away_score: 0 },
        { home: "Urawa Reds", away: "Machida", home_score: 1, away_score: 2 },
        { home: "Vissel Kobe", away: "Sanfreece", home_score: 2, away_score: 1 },
        { home: "Machida", away: "Kawasaki", home_score: 1, away_score: 1 },
        { home: "Machida", away: "FC Tokyo", home_score: 2, away_score: 0 },
        { home: "Vissel Kobe", away: "Shimizu", home_score: 2, away_score: 0 },
        { home: "JEF", away: "Tokyo Verdy", home_score: 3, away_score: 2 },
        { home: "Mito", away: "Kashima Antlers", home_score: 1, away_score: 1 },
        { home: "Nagoya", away: "Cerezo Osaka", home_score: 3, away_score: 0 },
        { home: "Gamba Osaka", away: "Kyoto", home_score: 2, away_score: 0 },
        { home: "Nagasaki", away: "Shimizu", home_score: 0, away_score: 3 },
        { home: "Okayama", away: "Vissel Kobe", home_score: 1, away_score: 4 },
        { home: "Kashiwa", away: "Yokohama FM", home_score: 3, away_score: 0 },
        { home: "Kawasaki", away: "Urawa Reds", home_score: 3, away_score: 2 },
        { home: "Chiba", away: "Avispa Fukuoka", home_score: 1, away_score: 2, date: "2026-06-07" },
        { home: "FC Tokyo", away: "Cerezo Osaka", home_score: 1, away_score: 3, date: "2026-06-07" },
        { home: "Machida", away: "Nagoya Grampus", home_score: 2, away_score: 1, date: "2026-06-07" },
        { home: "Mito", away: "V-Varen Nagasaki", home_score: 0, away_score: 1, date: "2026-06-07" },
        { home: "Urawa Reds", away: "Okayama", home_score: 0, away_score: 2, date: "2026-06-07" },
        { home: "Verdy", away: "Gamba Osaka", home_score: 2, away_score: 4, date: "2026-06-07" },
        { home: "Yokohama F. Marinos", away: "Shimizu S-Pulse", home_score: 3, away_score: 0, date: "2026-06-07" },
        { home: "Kashiwa Reysol", away: "Kyoto", home_score: 0, away_score: 1, date: "2026-06-07" },
        { home: "Kawasaki Frontale", away: "Sanfrecce Hiroshima", home_score: 0, away_score: 1, date: "2026-06-07" },
        { home: "Kashima Antlers", away: "Vissel Kobe", home_score: 2, away_score: 0, date: "2026-06-07" }
    ],

    "Japanese J2 League": [
        { home: "Consadole Sapporo", away: "Jubilo Iwata", home_score: 1, away_score: 0, date: "2026-06-06" },
        { home: "Fujieda MYFC", away: "Iwaki FC", home_score: 2, away_score: 1, date: "2026-06-06" },
        { home: "Albirex Niigata", away: "Hokkaido Consadole Sapporo", home_score: 0, away_score: 0, date: "2026-06-07", note: "Pen: 5-4" },
        { home: "Fujieda MYFC", away: "Ehime", home_score: 1, away_score: 0, date: "2026-06-07" },
        { home: "Omiya Ardija", away: "Kochi United", home_score: 2, away_score: 1, date: "2026-06-07" },
        { home: "Iwata", away: "Osaka", home_score: 2, away_score: 2, date: "2026-06-07", note: "Pen: 4-5" },
        { home: "Sagan Tosu", away: "Shonan Bellmare", home_score: 1, away_score: 0, date: "2026-06-07" },
        { home: "Sagamihara", away: "Kumamoto", home_score: 3, away_score: 0, date: "2026-06-07" },
        { home: "Tochigi City", away: "Reilac Shiga", home_score: 3, away_score: 1, date: "2026-06-07" },
        { home: "Yamaga", away: "Nara Club", home_score: 0, away_score: 2, date: "2026-06-07" },
        { home: "Yokohama FC", away: "Renofa Yamaguchi", home_score: 2, away_score: 1, date: "2026-06-07" },
        { home: "Gifu", away: "Gainare Tottori", home_score: 1, away_score: 1, date: "2026-06-07", note: "Pen: 2-4" }
    ],

    "Chinese Super League": [
        { home: "Qingdao Youth Island", away: "Tianjin Jinmen Tiger", home_score: 1, away_score: 1 },
        { home: "Shandong Taishan", away: "Shanghai Shenhua", home_score: 4, away_score: 1 },
        { home: "Shenyang Urban", away: "Chengdu Rongcheng", home_score: 0, away_score: 1 },
        { home: "Chongqing Tonglianglong", away: "Henan", home_score: 1, away_score: 1 },
        { home: "Wuhan Three Towns", away: "Qingdao Hainiu", home_score: 1, away_score: 3 },
        { home: "Beijing Guoan", away: "Dalian Yingbo", home_score: 3, away_score: 0 },
        { home: "Shanghai Port", away: "Shenzhen Peng City", home_score: 1, away_score: 1 },
        { home: "Yunnan Yukun", away: "Zhejiang", home_score: 1, away_score: 2 },
        { home: "Shanghai Shenhua", away: "Chongqing Tonglianglong", home_score: 2, away_score: 2 },
        { home: "Chengdu Rongcheng", away: "Henan", home_score: 3, away_score: 0 },
        { home: "Qingdao Youth Island", away: "Wuhan Three Towns", home_score: 1, away_score: 1 },
        { home: "Shenzhen Peng City", away: "Shandong Taishan", home_score: 1, away_score: 2 },
        { home: "Shenyang Urban", away: "Yunnan Yukun", home_score: 1, away_score: 2 },
        { home: "Zhejiang", away: "Tianjin Jinmen Tiger", home_score: 1, away_score: 1 },
        { home: "Beijing Guoan", away: "Shanghai Port", home_score: 2, away_score: 2 },
        { home: "Qingdao Hainiu", away: "Dalian Yingbo", home_score: 3, away_score: 1 },
        { home: "Henan", away: "Shenzhen Peng City", home_score: 1, away_score: 0 },
        { home: "Tianjin Jinmen Tiger", away: "Chengdu Rongcheng", home_score: 1, away_score: 2 },
        { home: "Shanghai Port", away: "Zhejiang", home_score: 2, away_score: 2 },
        { home: "Dalian Yingbo", away: "Qingdao Youth Island", home_score: 2, away_score: 3 },
        { home: "Beijing Guoan", away: "Qingdao Hainiu", home_score: 4, away_score: 2 },
        { home: "Wuhan Three Towns", away: "Shenyang Urban", home_score: 2, away_score: 2 },
        { home: "Shandong Taishan", away: "Chongqing Tonglianglong", home_score: 3, away_score: 1 },
        { home: "Yunnan Yukun", away: "Shanghai Shenhua", home_score: 1, away_score: 0 },
        { home: "Tianjin Jinmen Tiger", away: "Henan", home_score: 1, away_score: 2 },
        { home: "Shenzhen Peng City", away: "Dalian Yingbo", home_score: 1, away_score: 1 },
        { home: "Qingdao Youth Island", away: "Beijing Guoan", home_score: 1, away_score: 1 },
        { home: "Chengdu Rongcheng", away: "Shanghai Port", home_score: 0, away_score: 1 },
        { home: "Shenyang Urban", away: "Qingdao Hainiu", home_score: 2, away_score: 1 },
        { home: "Shanghai Shenhua", away: "Wuhan Three Towns", home_score: 2, away_score: 2 },
        { home: "Chongqing Tonglianglong", away: "Yunnan Yukun", home_score: 0, away_score: 0 },
        { home: "Zhejiang", away: "Shandong Taishan", home_score: 4, away_score: 1 },
        { home: "Shanghai Port", away: "Tianjin Jinmen Tiger", home_score: 1, away_score: 1 },
        { home: "Beijing Guoan", away: "Henan", home_score: 1, away_score: 2 },
        { home: "Dalian Yingbo", away: "Chengdu Rongcheng", home_score: 2, away_score: 0 },
        { home: "Qingdao Hainiu", away: "Chongqing Tonglianglong", home_score: 0, away_score: 1 },
        { home: "Yunnan Yukun", away: "Qingdao Youth Island", home_score: 2, away_score: 3 },
        { home: "Shandong Taishan", away: "Wuhan Three Towns", home_score: 3, away_score: 3 },
        { home: "Zhejiang", away: "Shenyang Urban", home_score: 0, away_score: 5 },
        { home: "Shanghai Shenhua", away: "Shenzhen Peng City", home_score: 1, away_score: 2 },
        { home: "Shenyang Urban", away: "Shanghai Port", home_score: 3, away_score: 2 },
        { home: "Qingdao Youth Island", away: "Shanghai Shenhua", home_score: 2, away_score: 2 },
        { home: "Henan", away: "Zhejiang", home_score: 0, away_score: 2 },
        { home: "Chengdu Rongcheng", away: "Shandong Taishan", home_score: 1, away_score: 0 },
        { home: "Chongqing Tonglianglong", away: "Beijing Guoan", home_score: 2, away_score: 3 },
        { home: "Shenzhen Peng City", away: "Qingdao Hainiu", home_score: 3, away_score: 2 },
        { home: "Tianjin Jinmen Tiger", away: "Dalian Yingbo", home_score: 1, away_score: 0 },
        { home: "Wuhan Three Towns", away: "Yunnan Yukun", home_score: 1, away_score: 1 }
    ]
};

console.log("? Complete matches data loaded successfully!");
console.log(`?? Loaded ${Object.keys(matchesData).length} leagues with match results`);