// ==================== COMPLETE MATCH RESULTS DATA ====================
// Converted from last.php - All actual match results for ALL leagues

const matchesData = {
    "English Premier League": [
        { home: "Manchester United", away: "Crystal Palace", home_score: 2, away_score: 1 },
        { home: "Brighton", away: "Nottingham", home_score: 1, away_score: 1 },
        { home: "Fulham", away: "Tottenham", home_score: 2, away_score: 1 },
        { home: "Arsenal", away: "Chelsea", home_score: 2, away_score: 1 },
        { home: "Bournemouth", away: "Brentford", home_score: 0, away_score: 0 },
        { home: "Everton", away: "Burnley", home_score: 2, away_score: 0 },
        { home: "Leeds", away: "Sunderland", home_score: 0, away_score: 1 },
        { home: "Wolves", away: "Liverpool", home_score: 2, away_score: 1 },
        { home: "Brighton", away: "Arsenal", home_score: 0, away_score: 1 },
        { home: "Fulham", away: "West Ham", home_score: 0, away_score: 1 },
        { home: "Manchester City", away: "Nottingham", home_score: 2, away_score: 2 },
        { home: "Aston Villa", away: "Chelsea", home_score: 1, away_score: 4 },
        { home: "Newcastle", away: "Manchester United", home_score: 2, away_score: 1 },
        { home: "Tottenham", away: "Crystal Palace", home_score: 1, away_score: 3 },
        { home: "Sunderland", away: "Brighton", home_score: 0, away_score: 1 },
        { home: "Burnley", away: "Bournemouth", home_score: 0, away_score: 0 },
        { home: "Chelsea", away: "Newcastle", home_score: 0, away_score: 1 },
        { home: "Arsenal", away: "Everton", home_score: 2, away_score: 0 },
        { home: "West Ham", away: "Manchester City", home_score: 1, away_score: 1 },
        { home: "Nottingham", away: "Fulham", home_score: 0, away_score: 0 },
        { home: "Manchester United", away: "Aston Villa", home_score: 3, away_score: 1 },
        { home: "Crystal Palace", away: "Leeds", home_score: 0, away_score: 0 },
        { home: "Liverpool", away: "Tottenham", home_score: 1, away_score: 1 },
        { home: "Brentford", away: "Wolves", home_score: 2, away_score: 2 },
        { home: "Bournemouth", away: "Manchester United", home_score: 2, away_score: 2 },
        { home: "Brighton", away: "Liverpool", home_score: 2, away_score: 1 },
        { home: "Fulham", away: "Burnley", home_score: 3, away_score: 1 },
        { home: "Everton", away: "Chelsea", home_score: 3, away_score: 0 },
        { home: "Leeds", away: "Brentford", home_score: 0, away_score: 0 },
        { home: "Newcastle", away: "Sunderland", home_score: 1, away_score: 2 },
        { home: "Aston Villa", away: "West Ham", home_score: 2, away_score: 0 },
        { home: "Tottenham", away: "Nottingham", home_score: 0, away_score: 3 },
        { home: "West Ham", away: "Wolves", home_score: 4, away_score: 0 },
        { home: "Arsenal", away: "Bournemouth", home_score: 1, away_score: 2 },
        { home: "Brentford", away: "Everton", home_score: 2, away_score: 2 },
        { home: "Burnley", away: "Brighton", home_score: 0, away_score: 2 },
        { home: "Liverpool", away: "Fulham", home_score: 2, away_score: 0 },
        { home: "Crystal Palace", away: "Newcastle", home_score: 2, away_score: 1 },
        { home: "Sunderland", away: "Tottenham", home_score: 1, away_score: 0 },
        { home: "Nottingham", away: "Aston Villa", home_score: 1, away_score: 1 },
        { home: "Chelsea", away: "Manchester City", home_score: 0, away_score: 3 },
        { home: "Manchester United", away: "Leeds", home_score: 1, away_score: 2 },
        { home: "Brentford", away: "Fulham", home_score: 0, away_score: 0 },
        { home: "Leeds", away: "Wolves", home_score: 3, away_score: 0 },
        { home: "Newcastle", away: "Bournemouth", home_score: 1, away_score: 2 },
        { home: "Chelsea", away: "Manchester United", home_score: 0, away_score: 1 },
        { home: "Nottingham", away: "Burnley", home_score: 0, away_score: 1 },
        { home: "Aston Villa", away: "Sunderland", home_score: 4, away_score: 3 },
        { home: "Everton", away: "Liverpool", home_score: 1, away_score: 2 },
        { home: "Manchester City", away: "Arsenal", home_score: 2, away_score: 1 },
        { home: "Crystal Palace", away: "West Ham", home_score: 0, away_score: 0 },
        { home: "Brighton", away: "Chelsea", home_score: 3, away_score: 0 },
        { home: "Burnley", away: "Manchester City", home_score: 0, away_score: 1 },
        { home: "Bournemouth", away: "Leeds", home_score: 2, away_score: 2 },
        { home: "Sunderland", away: "Nottingham", home_score: 0, away_score: 5 },
        { home: "Fulham", away: "Aston Villa", home_score: 1, away_score: 0 },
        { home: "West Ham", away: "Everton", home_score: 3, away_score: 0 },
        { home: "Wolves", away: "Tottenham", home_score: 0, away_score: 1 },
        { home: "Liverpool", away: "Crystal Palace", home_score: 3, away_score: 1 },
        { home: "Arsenal", away: "Newcastle", home_score: 1, away_score: 0 },
        { home: "Manchester United", away: "Brentford", home_score: 2, away_score: 1 },
        { home: "Leeds", away: "Burnley", home_score: 3, away_score: 1 },
        { home: "Brentford", away: "West Ham", home_score: 3, away_score: 0 },
        { home: "Wolves", away: "Sunderland", home_score: 1, away_score: 1 },
        { home: "Newcastle", away: "Brighton", home_score: 3, away_score: 1 },
        { home: "Arsenal", away: "Fulham", home_score: 3, away_score: 0 },
        { home: "Bournemouth", away: "Crystal Palace", home_score: 3, away_score: 0 },
        { home: "Manchester United", away: "Liverpool", home_score: 3, away_score: 2 },
        { home: "Aston Villa", away: "Tottenham", home_score: 1, away_score: 2 },
        { home: "Chelsea", away: "Nottingham", home_score: 1, away_score: 3 }
    ],

    "Spanish La Liga": [
        { home: "Osasuna", away: "Mallorca", home_score: 2, away_score: 2 },
        { home: "Levante", away: "Girona", home_score: 1, away_score: 1 },
        { home: "Atletico Madrid", away: "Real Sociedad", home_score: 3, away_score: 2 },
        { home: "Athletic Club", away: "Barcelona", home_score: 0, away_score: 1 },
        { home: "Villarreal", away: "Elche", home_score: 2, away_score: 1 },
        { home: "Getafe", away: "Real Betis", home_score: 0, away_score: 2 },
        { home: "Sevilla", away: "Rayo Vallecano", home_score: 1, away_score: 1 },
        { home: "Valencia", away: "Alaves", home_score: 3, away_score: 2 },
        { home: "Espanyol", away: "Oviedo", home_score: 1, away_score: 1 },
        { home: "Alaves", away: "Villarreal", home_score: 1, away_score: 1 },
        { home: "Girona", away: "Athletic Bilbao", home_score: 3, away_score: 0 },
        { home: "Athletic Club", away: "Getafe", home_score: 1, away_score: 0 },
        { home: "Oviedo", away: "Valencia", home_score: 1, away_score: 0 },
        { home: "Real Madrid", away: "Elche", home_score: 4, away_score: 1 },
        { home: "Mallorca", away: "Espanyol", home_score: 2, away_score: 1 },
        { home: "Barcelona", away: "Sevilla", home_score: 5, away_score: 2 },
        { home: "Real Betis", away: "Celta Vigo", home_score: 1, away_score: 1 },
        { home: "Real Sociedad", away: "Osasuna", home_score: 1, away_score: 2 },
        { home: "Rayo Vallecano", away: "Levante", home_score: 1, away_score: 1 },
        { home: "Villarreal", away: "Real Sociedad", home_score: 3, away_score: 1 },
        { home: "Elche", away: "Mallorca", home_score: 2, away_score: 1 },
        { home: "Espanyol", away: "Getafe", home_score: 1, away_score: 2 },
        { home: "Osasuna", away: "Girona", home_score: 1, away_score: 0 },
        { home: "Levante", away: "Oviedo", home_score: 4, away_score: 2 },
        { home: "Sevilla", away: "Valencia", home_score: 0, away_score: 2 },
        { home: "Barcelona", away: "Rayo Vallecano", home_score: 1, away_score: 0 },
        { home: "Celta Vigo", away: "Alaves", home_score: 3, away_score: 4 },
        { home: "Athletic Bilbao", away: "Real Betis", home_score: 2, away_score: 0 },
        { home: "Real Madrid", away: "Atletico Madrid", home_score: 3, away_score: 2 },
        { home: "Rayo Vallecano", away: "Elche", home_score: 1, away_score: 0 },
        { home: "Real Sociedad", away: "Levante", home_score: 2, away_score: 0 },
        { home: "Mallorca", away: "Real Madrid", home_score: 2, away_score: 1 },
        { home: "Real Betis", away: "Espanyol", home_score: 0, away_score: 0 },
        { home: "Atletico Madrid", away: "Barcelona", home_score: 1, away_score: 2 },
        { home: "Getafe", away: "Athletic Club", home_score: 2, away_score: 0 },
        { home: "Valencia", away: "Celta Vigo", home_score: 2, away_score: 3 },
        { home: "Oviedo", away: "Sevilla", home_score: 1, away_score: 0 },
        { home: "Alaves", away: "Osasuna", home_score: 2, away_score: 2 },
        { home: "Girona", away: "Villarreal", home_score: 1, away_score: 1 }
    ],

    "Italian Serie A": [
        { home: "Sassuolo", away: "Verona", home_score: 3, away_score: 0 },
        { home: "Juventus", away: "Como", home_score: 0, away_score: 2 },
        { home: "Leece", away: "Inter", home_score: 0, away_score: 2 },
        { home: "Cagliari", away: "Lazio", home_score: 0, away_score: 0 },
        { home: "Genoa", away: "Torino", home_score: 3, away_score: 0 },
        { home: "Atalanta", away: "Napoli", home_score: 2, away_score: 1 },
        { home: "Milan", away: "Parma", home_score: 0, away_score: 1 },
        { home: "Roma", away: "Cremonese", home_score: 3, away_score: 0 },
        { home: "Fiorentina", away: "Pisa", home_score: 1, away_score: 0 },
        { home: "Bologna", away: "Udinese", home_score: 1, away_score: 0 },
        { home: "Parma", away: "Cagliari", home_score: 1, away_score: 1 },
        { home: "Como", away: "Leece", home_score: 3, away_score: 1 },
        { home: "Verona", away: "Napoli", home_score: 1, away_score: 2 },
        { home: "Inter", away: "Genoa", home_score: 2, away_score: 0 },
        { home: "Cremonese", away: "Milan", home_score: 0, away_score: 2 },
        { home: "Sassuolo", away: "Atalanta", home_score: 2, away_score: 1 },
        { home: "Torino", away: "Lazio", home_score: 2, away_score: 0 },
        { home: "Roma", away: "Juventus", home_score: 3, away_score: 3 },
        { home: "Pisa", away: "Bologna", home_score: 0, away_score: 1 },
        { home: "Udinese", away: "Fiorentina", home_score: 3, away_score: 0 },
        { home: "Napoli", away: "Torino", home_score: 2, away_score: 1 },
        { home: "Cagliari", away: "Como", home_score: 1, away_score: 2 },
        { home: "Atalanta", away: "Udinese", home_score: 2, away_score: 2 },
        { home: "Juventus", away: "Pisa", home_score: 4, away_score: 0 },
        { home: "Leece", away: "Cremonese", home_score: 2, away_score: 1 },
        { home: "Bologna", away: "Verona", home_score: 1, away_score: 2 },
        { home: "Fiorentina", away: "Parma", home_score: 0, away_score: 0 },
        { home: "Genoa", away: "Roma", home_score: 2, away_score: 1 },
        { home: "Milan", away: "Inter", home_score: 1, away_score: 0 },
        { home: "Lazio", away: "Sassuolo", home_score: 2, away_score: 1 },
        { home: "Torino", away: "Parma", home_score: 4, away_score: 1 },
        { home: "Inter", away: "Atalanta", home_score: 1, away_score: 1 },
        { home: "Napoli", away: "Leece", home_score: 2, away_score: 1 },
        { home: "Udinese", away: "Juventus", home_score: 0, away_score: 1 },
        { home: "Verona", away: "Genoa", home_score: 0, away_score: 2 },
        { home: "Pisa", away: "Cagliari", home_score: 3, away_score: 1 },
        { home: "Sassuolo", away: "Bologna", home_score: 3, away_score: 1 },
        { home: "Como", away: "Roma", home_score: 2, away_score: 1 },
        { home: "Lazio", away: "Milan", home_score: 1, away_score: 0 },
        { home: "Cremonese", away: "Fiorentina", home_score: 1, away_score: 4 },
        { home: "Cagliari", away: "Napoli", home_score: 0, away_score: 1 },
        { home: "Genoa", away: "Udinese", home_score: 0, away_score: 2 },
        { home: "Parma", away: "Cremonese", home_score: 0, away_score: 2 },
        { home: "Milan", away: "Torino", home_score: 3, away_score: 2 },
        { home: "Juventus", away: "Sassuolo", home_score: 1, away_score: 1 },
        { home: "Como", away: "Pisa", home_score: 5, away_score: 0 },
        { home: "Atalanta", away: "Verona", home_score: 1, away_score: 0 },
        { home: "Bologna", away: "Lazio", home_score: 0, away_score: 2 },
        { home: "Roma", away: "Leece", home_score: 1, away_score: 0 },
        { home: "Fiorentina", away: "Inter", home_score: 1, away_score: 1 },
        { home: "Sassuolo", away: "Cagliari", home_score: 2, away_score: 1 },
        { home: "Verona", away: "Fiorentina", home_score: 0, away_score: 1 },
        { home: "Lazio", away: "Parma", home_score: 1, away_score: 1 },
        { home: "Pisa", away: "Torino", home_score: 1, away_score: 1 },
        { home: "Inter", away: "Roma", home_score: 5, away_score: 2 },
        { home: "Udinese", away: "Como", home_score: 0, away_score: 0 },
        { home: "Leece", away: "Atalanta", home_score: 0, away_score: 3 },
        { home: "Juventus", away: "Genoa", home_score: 2, away_score: 0 },
        { home: "Napoli", away: "Milan", home_score: 1, away_score: 0 },
        { home: "Roma", away: "Pisa", home_score: 3, away_score: 0 },
        { home: "Torino", away: "Verona", home_score: 2, away_score: 1 },
        { home: "Cagliari", away: "Cremonese", home_score: 1, away_score: 0 },
        { home: "Milan", away: "Udinese", home_score: 0, away_score: 3 },
        { home: "Atalanta", away: "Juventus", home_score: 0, away_score: 1 },
        { home: "Genoa", away: "Sassuolo", home_score: 2, away_score: 1 },
        { home: "Parma", away: "Napoli", home_score: 1, away_score: 1 },
        { home: "Bologna", away: "Leece", home_score: 2, away_score: 0 },
        { home: "Como", away: "Inter", home_score: 3, away_score: 4 },
        { home: "Fiorentina", away: "Lazio", home_score: 1, away_score: 0 }
    ],

    "French Ligue 1": [
        { home: "Strasbourg", away: "Lens", home_score: 1, away_score: 1 },
        { home: "Rennes", away: "Toulouse", home_score: 1, away_score: 0 },
        { home: "Monaco", away: "Angers", home_score: 2, away_score: 0 },
        { home: "Le Havre", away: "PSG", home_score: 0, away_score: 1 },
        { home: "Paris", away: "Nice", home_score: 1, away_score: 0 },
        { home: "Lorient", away: "Auxerre", home_score: 2, away_score: 2 },
        { home: "Lille", away: "Nantes", home_score: 1, away_score: 0 },
        { home: "Metz", away: "Brest", home_score: 0, away_score: 1 },
        { home: "Marseille", away: "Lyon", home_score: 3, away_score: 2 },
        { home: "PSG", away: "Monaco", home_score: 1, away_score: 3 },
        { home: "Nantes", away: "Angers", home_score: 0, away_score: 1 },
        { home: "Auxerre", away: "Strasbourg", home_score: 0, away_score: 0 },
        { home: "Toulouse", away: "Marseille", home_score: 0, away_score: 1 },
        { home: "Lens", away: "Metz", home_score: 3, away_score: 0 },
        { home: "Lille", away: "Lorient", home_score: 1, away_score: 1 },
        { home: "Brest", away: "Le Havre", home_score: 2, away_score: 0 },
        { home: "Nice", away: "Rennes", home_score: 0, away_score: 4 },
        { home: "Lyon", away: "Paris", home_score: 1, away_score: 1 },
        { home: "Marseille", away: "Auxerre", home_score: 1, away_score: 0 },
        { home: "Lorient", away: "Lens", home_score: 2, away_score: 1 },
        { home: "Monaco", away: "Brest", home_score: 2, away_score: 0 },
        { home: "Strasbourg", away: "Paris", home_score: 0, away_score: 0 },
        { home: "Metz", away: "Toulouse", home_score: 3, away_score: 4 },
        { home: "Le Havre", away: "Lyon", home_score: 0, away_score: 0 },
        { home: "Rennes", away: "Lille", home_score: 1, away_score: 2 },
        { home: "Angers", away: "Brest", home_score: 5, away_score: 1 },
        { home: "Toulouse", away: "Lorient", home_score: 1, away_score: 0 },
        { home: "Auxerre", away: "Brest", home_score: 3, away_score: 0 },
        { home: "Nice", away: "PSG", home_score: 0, away_score: 4 },
        { home: "Lyon", away: "Monaco", home_score: 1, away_score: 2 },
        { home: "Rennes", away: "Metz", home_score: 0, away_score: 0 },
        { home: "Paris", away: "Le Havre", home_score: 3, away_score: 2 },
        { home: "Marseille", away: "Lille", home_score: 1, away_score: 2 },
        { home: "Nantes", away: "Strasbourg", home_score: 2, away_score: 3 },
        { home: "PSG", away: "Toulouse", home_score: 3, away_score: 1 },
        { home: "Strasbourg", away: "Nice", home_score: 3, away_score: 1 },
        { home: "Brest", away: "Rennes", home_score: 3, away_score: 4 },
        { home: "Lille", away: "Lens", home_score: 3, away_score: 0 },
        { home: "Angers", away: "Lyon", home_score: 0, away_score: 0 },
        { home: "Metz", away: "Nantes", home_score: 0, away_score: 0 },
        { home: "Lorient", away: "Paris", home_score: 1, away_score: 1 },
        { home: "Le Havre", away: "Auxerre", home_score: 1, away_score: 1 },
        { home: "Monaco", away: "Marseille", home_score: 2, away_score: 1 },
        { home: "Paris", away: "Monaco", home_score: 4, away_score: 1 }
    ],

    "German Bundesliga": [
        { home: "Stuttgart", away: "Wolfsburg", home_score: 4, away_score: 0 },
        { home: "Frankfurt", away: "Freiburg", home_score: 2, away_score: 0 },
        { home: "Hamburger", away: "Leipzig", home_score: 1, away_score: 2 },
        { home: "Hamburger", away: "Leverkusen", home_score: 0, away_score: 1 },
        { home: "Bayern", away: "Monchengladbach", home_score: 4, away_score: 1 },
        { home: "Leipzig", away: "Augsburg", home_score: 2, away_score: 1 },
        { home: "Wolfsburg", away: "Hamburger", home_score: 1, away_score: 2 },
        { home: "Freiburg", away: "Leverkusen", home_score: 3, away_score: 3 },
        { home: "Heidenheim", away: "Hoffenheim", home_score: 2, away_score: 4 },
        { home: "Koln", away: "Dortmund", home_score: 1, away_score: 2 },
        { home: "St. Pauli", away: "Frankfurt", home_score: 0, away_score: 0 },
        { home: "Union Berlin", away: "Werder", home_score: 1, away_score: 4 },
        { home: "Monchengladbach", away: "St. Pauli", home_score: 2, away_score: 0 },
        { home: "Frankfurt", away: "Heidenheim", home_score: 1, away_score: 0 },
        { home: "Dortmund", away: "Augsburg", home_score: 2, away_score: 0 },
        { home: "Leverkusen", away: "Bayern", home_score: 1, away_score: 1 },
        { home: "Hoffenheim", away: "Wolfsburg", home_score: 1, away_score: 1 },
        { home: "St. Hamburger", away: "Koln", home_score: 1, away_score: 1 },
        { home: "Werder", away: "Mainz", home_score: 0, away_score: 2 },
        { home: "Freiburg", away: "Union Berlin", home_score: 0, away_score: 1 },
        { home: "Stuttgart", away: "Leipzig", home_score: 1, away_score: 0 },
        { home: "Leipzig", away: "Hoffenheim", home_score: 5, away_score: 0 },
        { home: "Wolfsburg", away: "Werder", home_score: 0, away_score: 1 },
        { home: "Koln", away: "Monchengladbach", home_score: 3, away_score: 3 },
        { home: "Dortmund", away: "Hamburger", home_score: 3, away_score: 2 },
        { home: "Mainz", away: "Frankfurt", home_score: 2, away_score: 1 },
        { home: "St. Pauli", away: "Freiburg", home_score: 1, away_score: 2 },
        { home: "Augsburg", away: "Stuttgart", home_score: 2, away_score: 5 },
        { home: "Freiburg", away: "Bayern", home_score: 2, away_score: 3 },
        { home: "Hoffenheim", away: "Mainz", home_score: 1, away_score: 2 },
        { home: "Werder", away: "Leipzig", home_score: 1, away_score: 2 },
        { home: "Hamburger", away: "Augsburg", home_score: 1, away_score: 1 },
        { home: "Monchengladbach", away: "Heidenheim", home_score: 2, away_score: 2 },
        { home: "Leverkusen", away: "Wolfsburg", home_score: 6, away_score: 3 },
        { home: "Stuttgart", away: "Dortmund", home_score: 0, away_score: 2 },
        { home: "Union Berlin", away: "St. Pauli", home_score: 1, away_score: 1 },
        { home: "Frankfurt", away: "Koln", home_score: 2, away_score: 2 },
        { home: "Augsburg", away: "Hoffenheim", home_score: 2, away_score: 2 }
    ],

    "Netherland Eredivisie": [
        { home: "Heracles", away: "Utrecht", home_score: 0, away_score: 0 },
        { home: "Groningen", away: "Ajax", home_score: 3, away_score: 1 },
        { home: "Excelsior", away: "Heerenveen", home_score: 1, away_score: 2 },
        { home: "PSV", away: "AZ Alkmaar", home_score: 2, away_score: 1 },
        { home: "Sparta Rotterdam", away: "Zwolle", home_score: 1, away_score: 1 },
        { home: "Fortuna Sittard", away: "Telstar", home_score: 1, away_score: 4 },
        { home: "Go Ahead Eagles", away: "Twente", home_score: 1, away_score: 4 },
        { home: "NAC", away: "Feyenoord", home_score: 3, away_score: 3 },
        { home: "NEC", away: "Volendam", home_score: 3, away_score: 0 },
        { home: "Zwolle", away: "Groningen", home_score: 1, away_score: 1 },
        { home: "Volendam", away: "Fortuna Sittard", home_score: 1, away_score: 2 },
        { home: "PSV", away: "NEC", home_score: 2, away_score: 3 },
        { home: "Heerenveen", away: "Telstar", home_score: 3, away_score: 0 },
        { home: "Ajax", away: "Sparta Rotterdam", home_score: 4, away_score: 0 },
        { home: "Twente", away: "Utrecht", home_score: 0, away_score: 2 },
        { home: "AZ Alkmaar", away: "Heracles", home_score: 4, away_score: 0 },
        { home: "Feyenoord", away: "Excelsior", home_score: 2, away_score: 1 },
        { home: "Go Ahead Eagles", away: "NAC", home_score: 6, away_score: 0 }
    ],

    "Belgian Pro League": [
        { home: "La Louviere", away: "Antwerp", home_score: 0, away_score: 0 },
        { home: "Oud Herverlee Leuven", away: "Westerlo", home_score: 0, away_score: 1 },
        { home: "Dender", away: "Charleroi", home_score: 2, away_score: 2 },
        { home: "Union Saint Gilloise", away: "Genk", home_score: 2, away_score: 1 },
        { home: "Club Brugge", away: "Anderlecht", home_score: 2, away_score: 2 },
        { home: "Gent", away: "Mechelen", home_score: 3, away_score: 1 },
        { home: "Zulte Waregem", away: "Standard", home_score: 0, away_score: 1 },
        { home: "STVV", away: "Cercle Brugge", home_score: 2, away_score: 1 },
        { home: "Gent", away: "Zulte Waregem", home_score: 2, away_score: 0 },
        { home: "Charleroi", away: "Oud Herverlee Leuven", home_score: 0, away_score: 2 },
        { home: "Union Saint Gilloise", away: "Dender", home_score: 2, away_score: 0 },
        { home: "Westerlo", away: "Club Brugge", home_score: 1, away_score: 2 },
        { home: "Genk", away: "STVV", home_score: 2, away_score: 1 },
        { home: "Antwerp", away: "Standard", home_score: 1, away_score: 1 },
        { home: "Mechelen", away: "Anderlecht", home_score: 1, away_score: 0 },
        { home: "Cercle Brugge", away: "La Louviere", home_score: 1, away_score: 3 },
        { home: "Club Brugge", away: "Mechelen", home_score: 4, away_score: 1 },
        { home: "Dender", away: "Gent", home_score: 1, away_score: 3 },
        { home: "Standard", away: "Westerlo", home_score: 0, away_score: 0 },
        { home: "Zulte Waregem", away: "Charleroi", home_score: 1, away_score: 0 },
        { home: "Anderlecht", away: "Cercle Brugge", home_score: 2, away_score: 3 },
        { home: "La Louviere", away: "Genk", home_score: 5, away_score: 5 },
        { home: "STVV", away: "Union Saint Gilloise", home_score: 1, away_score: 3 },
        { home: "Oud Heverlee Leuven", away: "Antwerp", home_score: 1, away_score: 0 }
    ],

    "Portuguese Primeira Liga": [
        { home: "Familicao", away: "Arouca", home_score: 1, away_score: 0 },
        { home: "Moreirense", away: "Arouca", home_score: 1, away_score: 1 },
        { home: "Alverca", away: "AVS", home_score: 0, away_score: 0 },
        { home: "Braga", away: "Sporting", home_score: 2, away_score: 2 },
        { home: "Estoril", away: "Casa Pia", home_score: 0, away_score: 0 },
        { home: "Estrela", away: "Gil Vicente", home_score: 2, away_score: 2 },
        { home: "Benfica", away: "Porto", home_score: 2, away_score: 2 },
        { home: "Santa Clara", away: "Vitoria", home_score: 2, away_score: 0 },
        { home: "Tondela", away: "Rio Ave", home_score: 0, away_score: 1 },
        { home: "Vitoria", away: "Familicao", home_score: 1, away_score: 2 },
        { home: "Gil Vicente", away: "Alverca", home_score: 2, away_score: 2 },
        { home: "Arouca", away: "Benfica", home_score: 1, away_score: 2 },
        { home: "AVS", away: "Santa Clara", home_score: 0, away_score: 1 },
        { home: "Nacional", away: "Estoril", home_score: 0, away_score: 1 },
        { home: "Rio Ave", away: "Estrela", home_score: 2, away_score: 1 },
        { home: "Porto", away: "Moreirense", home_score: 3, away_score: 0 }
    ],

    "English Championship": [
        { home: "Wrexham", away: "Hull", home_score: 1, away_score: 2 },
        { home: "Sheffield Wednesday", away: "Watford", home_score: 1, away_score: 1 },
        { home: "Leicester", away: "Bristol City", home_score: 2, away_score: 0 },
        { home: "Portsmouth", away: "Swansea", home_score: 1, away_score: 2 },
        { home: "Millwall", away: "Derby County", home_score: 1, away_score: 0 },
        { home: "Stoke", away: "Ipswich", home_score: 3, away_score: 3 },
        { home: "Oxford", away: "Blackburn", home_score: 1, away_score: 0 },
        { home: "West Brom", away: "Southampton", home_score: 1, away_score: 1 },
        { home: "Middlesbrough", away: "Charlton", home_score: 0, away_score: 1 },
        { home: "Norwich", away: "Sheffield United", home_score: 2, away_score: 1 },
        { home: "Birmingham", away: "QPR", home_score: 1, away_score: 0 },
        { home: "Coventry", away: "Preston", home_score: 3, away_score: 0 }
    ],

    "Australia A-League": [
        { home: "Melbourne Victory", away: "Adelaide United", home_score: 1, away_score: 1 },
        { home: "Auckland", away: "Melbourne City", home_score: 3, away_score: 0 },
        { home: "Central Coast", away: "Newcastle Jets", home_score: 0, away_score: 0 },
        { home: "Brisbane Roar", away: "Perth Glory", home_score: 1, away_score: 1 },
        { home: "Macarthur", away: "Western Sydney", home_score: 0, away_score: 4 },
        { home: "Wellington Phoenix", away: "Sydney FC", home_score: 0, away_score: 1 }
    ],

    "English League One": [
        { home: "Rotherham", away: "Bolton", home_score: 2, away_score: 2 },
        { home: "Lincoln", away: "Stockport", home_score: 3, away_score: 1 },
        { home: "Leyton Orient", away: "Peterborough", home_score: 2, away_score: 1 },
        { home: "Reading", away: "Plymouth", home_score: 2, away_score: 2 },
        { home: "Wycombe", away: "Luton", home_score: 1, away_score: 2 },
        { home: "Northampton", away: "Burton", home_score: 0, away_score: 2 },
        { home: "Stevenage", away: "Wimbledon", home_score: 1, away_score: 0 },
        { home: "Port Vale", away: "Huddersfield", home_score: 0, away_score: 0 },
        { home: "Wigan", away: "Bradford", home_score: 2, away_score: 0 },
        { home: "Mansfield", away: "Barnsley", home_score: 2, away_score: 2 }
    ],

    "English League Two": [
        { home: "Newport", away: "Bromley", home_score: 0, away_score: 1 },
        { home: "Accrington Stanley", away: "Notts County", home_score: 0, away_score: 4 },
        { home: "Bristol Rovers", away: "Shrewsbury", home_score: 1, away_score: 0 },
        { home: "Gillingham", away: "Swindon", home_score: 0, away_score: 2 },
        { home: "Walsall", away: "Cambridge", home_score: 0, away_score: 0 },
        { home: "Cheltenham", away: "Crewe", home_score: 1, away_score: 1 },
        { home: "Tranmere", away: "Harrogate", home_score: 0, away_score: 3 },
        { home: "Salford", away: "Barrow", home_score: 3, away_score: 1 },
        { home: "Chesterfield", away: "Oldham", home_score: 0, away_score: 3 },
        { home: "Crawley", away: "Barnet", home_score: 1, away_score: 1 },
        { home: "Grimsby", away: "Fleetwood", home_score: 1, away_score: 0 },
        { home: "MK Dons", away: "Colchester", home_score: 1, away_score: 0 }
    ],

    "La Liga 2": [
        { home: "Mirandes", away: "Cadiz", home_score: 0, away_score: 2 },
        { home: "Cultural Leonesa", away: "Racing", home_score: 1, away_score: 2 },
        { home: "Valladolid", away: "Leganes", home_score: 3, away_score: 2 },
        { home: "Zaragoza", away: "Almeria", home_score: 2, away_score: 0 },
        { home: "Ceuta", away: "Deportivo", home_score: 1, away_score: 2 },
        { home: "Cordoba", away: "Real Sociedad B", home_score: 2, away_score: 0 },
        { home: "Granada", away: "Andorra", home_score: 1, away_score: 1 },
        { home: "Malaga", away: "Huesca", home_score: 5, away_score: 3 },
        { home: "Eibar", away: "Burgos", home_score: 0, away_score: 0 },
        { home: "Gijon", away: "Castellon", home_score: 4, away_score: 1 },
        { home: "Albacete", away: "Las Palmas", home_score: 2, away_score: 1 }
    ],

    "Italian Serie B": [
        { home: "Modena", away: "Spezia", home_score: 3, away_score: 0 },
        { home: "Bari", away: "Reggiana", home_score: 4, away_score: 1 },
        { home: "Padova", away: "Catanzaro", home_score: 1, away_score: 3 },
        { home: "Cesena", away: "Frisonone", home_score: 2, away_score: 2 },
        { home: "Juve Stabia", away: "Carrarese", home_score: 1, away_score: 1 },
        { home: "Empoli", away: "Mantova", home_score: 2, away_score: 2 },
        { home: "Monza", away: "Palermo", home_score: 3, away_score: 0 },
        { home: "Sampdoria", away: "Venezia", home_score: 0, away_score: 0 },
        { home: "Virtus Entella", away: "Avellino", home_score: 1, away_score: 2 },
        { home: "Sudtirol", away: "Pescara", home_score: 0, away_score: 0 }
    ],

    "French Ligue 2": [
        { home: "Rodez", away: "Grenoble", home_score: 1, away_score: 0 },
        { home: "Laval", away: "Guingamp", home_score: 2, away_score: 3 },
        { home: "Nancy", away: "Montpellier", home_score: 0, away_score: 3 },
        { home: "Boulogne", away: "Amiens", home_score: 4, away_score: 2 },
        { home: "Le Mans", away: "Annecy", home_score: 3, away_score: 0 },
        { home: "Troyes", away: "Clermont Foot", home_score: 3, away_score: 0 },
        { home: "St. Etienne", away: "Red Star", home_score: 2, away_score: 0 },
        { home: "Dunkerque", away: "Reims", home_score: 1, away_score: 1 }
    ],

    "German Bundesliga 2": [
        { home: "Elvesberg", away: "Magdeburg", home_score: 1, away_score: 0 },
        { home: "Schalke", away: "Arminia", home_score: 1, away_score: 0 },
        { home: "Padeborn", away: "Braunschweig", home_score: 1, away_score: 1 },
        { home: "Nurnberg", away: "Dusseldorf", home_score: 0, away_score: 1 },
        { home: "Darmstadt", away: "Holstein Kiel", home_score: 2, away_score: 0 },
        { home: "Bochum", away: "Kaiserslautern", home_score: 3, away_score: 2 },
        { home: "Hannover", away: "Greuther Furth", home_score: 1, away_score: 2 },
        { home: "Karlsruher", away: "Dynamo", home_score: 3, away_score: 3 }
    ],

    "Eerste Divisie": [
        { home: "Eindhoven", away: "Jong Ajax", home_score: 2, away_score: 1 },
        { home: "Dordrecht", away: "MVV", home_score: 1, away_score: 1 },
        { home: "VVV", away: "Waalwijk", home_score: 0, away_score: 3 },
        { home: "Roda", away: "Jong PSV", home_score: 0, away_score: 2 },
        { home: "Helmond", away: "TOP Oss", home_score: 1, away_score: 1 },
        { home: "Jong Ajax", away: "Dordrecht", home_score: 0, away_score: 0 },
        { home: "Almere", away: "Den Haag", home_score: 1, away_score: 0 },
        { home: "De Graafschap", away: "Vitesse", home_score: 1, away_score: 4 },
        { home: "Wilhelm II", away: "Den Bosch", home_score: 1, away_score: 1 }
    ],

    "Belgian Challenger Pro League": [
        { home: "Beerschot", away: "RSCA FUTURES", home_score: 4, away_score: 2 },
        { home: "Eupen", away: "Lierse K", home_score: 0, away_score: 1 },
        { home: "Patro Eisden", away: "Liege", home_score: 0, away_score: 1 },
        { home: "Jong Genk", away: "Club NXT", home_score: 0, away_score: 0 },
        { home: "Beveren", away: "Daring Brussels", home_score: 3, away_score: 2 },
        { home: "Jong Gent", away: "Lommel", home_score: 2, away_score: 2 },
        { home: "ROC Charleroi", away: "Seraing", home_score: 2, away_score: 4 },
        { home: "Francs Borains", away: "Lokeren-Temse", home_score: 1, away_score: 0 },
        { home: "Lierse K", away: "Patro Eisden", home_score: 1, away_score: 2 },
        { home: "RSCA FUTURES", away: "Eupen", home_score: 0, away_score: 1 }
    ],

    "Argentine Liga Profesional": [
        { home: "Tigre", away: "Velez Sarsfield", home_score: 1, away_score: 1 },
        { home: "Independiente", away: "Union", home_score: 4, away_score: 4 },
        { home: "Sarmiento", away: "Racing Club", home_score: 0, away_score: 0 },
        { home: "Newells", away: "Platense", home_score: 1, away_score: 1 },
        { home: "Argentinos Juniors", away: "Central", home_score: 0, away_score: 0 },
        { home: "Banfield", away: "Gimnasia LP", home_score: 1, away_score: 2 },
        { home: "Boca Juniors", away: "San Lorenzo", home_score: 1, away_score: 1 },
        { home: "Independiente Rivadavia", away: "Barracas Central", home_score: 1, away_score: 2 },
        { home: "Atletico Tucuman", away: "Aldosivi", home_score: 1, away_score: 1 },
        { home: "Defensa", away: "Central Cordoba", home_score: 1, away_score: 1 },
        { home: "Riestra", away: "Gimnasia Esgrima", home_score: 0, away_score: 0 }
    ],
	"Argentine Primera B Metropolitana": [
    // Matchday 5
    { home: "Deportivo Camioneros", away: "Villa San Carlos", home_score: 3, away_score: 0 },
    
    // Matchday 17
    { home: "Argentino de Merlo", away: "San Martín Burzaco", home_score: 0, away_score: 1 },
    
    // Matchday 5 (continued)
    { home: "Dep. Armenio", away: "Argentino de Merlo", home_score: 2, away_score: 0 },
    { home: "Flandria", away: "Arsenal Sarandi", home_score: 0, away_score: 0 },
    { home: "Dock Sud", away: "Real Pilar", home_score: 2, away_score: 0 },
    { home: "Brown (A)", away: "Talleres Remedios", home_score: 1, away_score: 2 },
    { home: "Deportivo Merlo", away: "Liniers", home_score: 0, away_score: 0 },
    { home: "Comunicaciones", away: "UAI Urquiza", home_score: 3, away_score: 0 },
    { home: "Ituzaingó", away: "Laferrere", home_score: 0, away_score: 2 },
    { home: "Sportivo Italiano", away: "San Martín Burzaco", home_score: 1, away_score: 2 },
    { home: "Defensores Unidos", away: "Dálmine", home_score: 2, away_score: 1 },
    { home: "Argentino Quilmes", away: "Excursionistas", home_score: 2, away_score: 2 },
    
    // Matchday 18
    { home: "Comunicaciones", away: "Dep. Armenio", home_score: 0, away_score: 1 },
    { home: "Dock Sud", away: "Brown (A)", home_score: 0, away_score: 1 },
    { home: "Real Pilar", away: "UAI Urquiza", home_score: 2, away_score: 1 },
    { home: "Liniers", away: "Dálmine", home_score: 1, away_score: 0 },
    { home: "Deportivo Camioneros", away: "Talleres Remedios", home_score: 1, away_score: 4 },
    { home: "Sportivo Italiano", away: "Argentino de Merlo", home_score: 0, away_score: 2 },
    { home: "Villa San Carlos", away: "Excursionistas", home_score: 0, away_score: 2 },
    { home: "Defensores Unidos", away: "Flandria", home_score: 1, away_score: 0 },
	{ home: "San Martín Burzaco", away: "Arsenal Sarandi", home_score: 2, away_score: 0 },
	{ home: "Argentino Quilmes", away: "Ituzaingó", home_score: 2, away_score: 0 },

    "MLS USA": [
        { home: "New York City", away: "Orlando", home_score: 5, away_score: 0 },
        { home: "DC United", away: "Inter Miami", home_score: 1, away_score: 2 },
        { home: "Philadelphia", away: "San Jose", home_score: 0, away_score: 1 },
        { home: "Charlotte", away: "Austin", home_score: 3, away_score: 1 },
        { home: "Atlanta", away: "Real Salt Lake", home_score: 2, away_score: 3 },
        { home: "Columbus", away: "Chicago", home_score: 0, away_score: 0 },
        { home: "Sporting KC", away: "San Diego", home_score: 0, away_score: 1 },
        { home: "St. Louis", away: "Seattle", home_score: 0, away_score: 1 },
        { home: "Nashville", away: "Minnesota", home_score: 0, away_score: 1 },
        { home: "Colorado", away: "LA Galaxy", home_score: 4, away_score: 1 },
        { home: "Portland", away: "Vancouver", home_score: 1, away_score: 4 },
        { home: "LAFC", away: "Dallas", home_score: 1, away_score: 0 },
        { home: "NY Red Bulls", away: "Montreal", home_score: 0, away_score: 3 },
        { home: "Cincinnati", away: "Toronto", home_score: 0, away_score: 1 }
    ],

    "Japanese J1 League": [
        { home: "JEF", away: "Kashiwa", home_score: 2, away_score: 1 },
        { home: "FC Tokyo", away: "Yokohama FM", home_score: 3, away_score: 0 },
        { home: "Urawa Reds", away: "Mito", home_score: 2, away_score: 0 },
        { home: "Kashima Antlers", away: "Tokyo Verdy", home_score: 2, away_score: 0 },
        { home: "Avispa", away: "Nagoya", home_score: 1, away_score: 5 },
        { home: "Okayama", away: "Kyoto", home_score: 1, away_score: 0 },
        { home: "Gamba Osaka", away: "Nagasaki", home_score: 3, away_score: 2 },
        { home: "Yokohama FM", away: "JEF", home_score: 2, away_score: 0 },
        { home: "Kyoto", away: "Cerezo Osaka", home_score: 1, away_score: 2 },
        { home: "Shimizu", away: "Okayama", home_score: 1, away_score: 1 },
        { home: "Kashiwa", away: "Machida", home_score: 0, away_score: 1 },
        { home: "Nagoya", away: "Vissel Kobe", home_score: 0, away_score: 3 },
		{ home: "Mito", away: "FC Tokyo", home_score: 1, away_score: 1 },
		{ home: "Kashima Antlers", away: "Kawasaki", home_score: 1, away_score: 0 },
		{ home: "Nagasaki", away: "Avispa", home_score: 1, away_score: 0 },
		{ home: "Cerezo Osaka", away: "Okayama", home_score: 1, away_score: 2 },
		{ home: "Vissel Kobe", away: "Gamba Osaka", home_score: 2, away_score: 2 },
		{ home: "Mito", away: "Yokohama FM", home_score: 1, away_score: 0 },
		{ home: "Avispa", away: "Shimizu", home_score: 1, away_score: 1 },
		{ home: "Nagoya", away: "Sanfreece", home_score: 2, away_score: 1 },
		{ home: "JEF", away: "FC Tokyo", home_score: 1, away_score: 2 },
		{ home: "Nagasaki", away: "Kyoto", home_score: 1, away_score: 2 },
		{ home: "Tokyo Verdy", away: "Kawasaki", home_score: 0, away_score: 2 },
		{ home: "Machida", away: "Kashima Antlers", home_score: 0, away_score: 3 },
		{ home: "Urawa Reds", away: "Kashiwa", home_score: 1, away_score: 1 },
		{ home: "Okayama", away: "Nagasaki", home_score: 0, away_score: 1 },
		{ home: "Avispa", away: "Gamba Osaka", home_score: 2, away_score: 2 },
		{ home: "Shimizu", away: "Sanfreece", home_score: 3, away_score: 1 },
		{ home: "Kyoto", away: "Nagoya", home_score: 1, away_score: 1 },
		{ home: "Tokyo Verdy", away: "FC Tokyo", home_score: 0, away_score: 0 },
		{ home: "Cerezo Osaka", away: "Vissel Kobe", home_score: 1, away_score: 1 },
		{ home: "Kashima Antlers", away: "JEF", home_score: 2, away_score: 1 },
		{ home: "Kawasaki", away: "Yokohama FM", home_score: 0, away_score: 5 },
		{ home: "Kashiwa", away: "Mito", home_score: 3, away_score: 0 },
		{ home: "Urawa Reds", away: "Machida", home_score: 1, away_score: 2 },
		{ home: "Vissel Kobe", away: "Sanfreece", home_score: 2, away_score: 1 },
		{ home: "Machida", away: "Kawasaki", home_score: 1, away_score: 1 },
		{ home: "Machida", away: "FC Tokyo", home_score: 2, away_score: 0 },
		{ home: "Vissel Kobe", away: "Shimizu", home_score: 2, away_score: 0 },
		{ home: "JEF", away: "Tokyo Verdy", home_score: 3, away_score: 2 },
		{ home: "Mito", away: "Kashima Antlers", home_score: 1, away_score: 1 },{ home: "Nagoya", away: "Cerezo Osaka", home_score: 3, away_score: 0 },
		{ home: "Gamba Osaka", away: "Kyoto", home_score: 2, away_score: 0 },
		{ home: "Nagasaki", away: "Shimizu", home_score: 0, away_score: 3 },
		{ home: "Okayama", away: "Vissel Kobe", home_score: 1, away_score: 4 },
		{ home: "Kashiwa", away: "Yokohama FM", home_score: 3, away_score: 0 },
		{ home: "Kawasaki", away: "Urawa Reds", home_score: 3, away_score: 2 },
    ],
	
	"Chilean Primera División": [
    // Matchday 12
    { home: "Palestino", away: "La Serena", home_score: 5, away_score: 1 },
    { home: "Coquimbo", away: "Audax Italiano", home_score: 3, away_score: 0 },
    { home: "O'Higgins", away: "Universidad de Concepción", home_score: 0, away_score: 1 },
    { home: "Deportes Limache", away: "Universidad Católica", home_score: 0, away_score: 2 },
    { home: "Huachipato", away: "Unión La Calera", home_score: 3, away_score: 1 },
    { home: "Cobresal", away: "Universidad de Chile", home_score: 1, away_score: 0 },
    { home: "Colo-Colo", away: "Ñublense", home_score: 6, away_score: 2 },
    { home: "Concepción", away: "Everton", home_score: 0, away_score: 2 },
    
    // Matchday 13
    { home: "Everton", away: "Coquimbo", home_score: 1, away_score: 1 },
    { home: "Audax Italiano", away: "Cobresal", home_score: 2, away_score: 1 },
    { home: "Ñublense", away: "Universidad de Concepción", home_score: 2, away_score: 2 },
    { home: "Unión La Calera", away: "Palestino", home_score: 1, away_score: 2 },
    { home: "Concepción", away: "Huachipato", home_score: 2, away_score: 0 },
    { home: "La Serena", away: "Deportes Limache", home_score: 4, away_score: 1 },
    { home: "Universidad Católica", away: "Colo-Colo", home_score: 1, away_score: 2 },
    
    // Matchday 14
    { home: "Cobresal", away: "Ñublense", home_score: 0, away_score: 1 },
    { home: "Universidad de Concepción", away: "Unión La Calera", home_score: 0, away_score: 0 },
    { home: "La Serena", away: "Colo-Colo", home_score: 2, away_score: 4 },
	{ home: "Universidad de Concepción", away: "Concepción", home_score: 2, away_score: 1 },
	{ home: "Deportes Limache", away: "Coquimbo", home_score: 2, away_score: 3 },
	{ home: "Huachipato", away: "Universidad Católica", home_score: 0, away_score: 3 },
	{ home: "O'Higgins", away: "Everton", home_score: 2, away_score: 3 },
	{ home: "Palestino", away: "Audax Italiano", home_score: 0, away_score: 0 },
],
"Chinese Super League": [
    // Matchday 10
    { home: "Qingdao Youth Island", away: "Tianjin Jinmen Tiger", home_score: 1, away_score: 1 },
    { home: "Shandong Taishan", away: "Shanghai Shenhua", home_score: 4, away_score: 1 },
    { home: "Shenyang Urban", away: "Chengdu Rongcheng", home_score: 0, away_score: 1 },
    { home: "Chongqing Tonglianglong", away: "Henan", home_score: 1, away_score: 1 },
    { home: "Wuhan Three Towns", away: "Qingdao Hainiu", home_score: 1, away_score: 3 },
    { home: "Beijing Guoan", away: "Dalian Yingbo", home_score: 3, away_score: 0 },
    { home: "Shanghai Port", away: "Shenzhen Peng City", home_score: 1, away_score: 1 },
    { home: "Yunnan Yukun", away: "Zhejiang", home_score: 1, away_score: 2 },
    
    // Matchday 11
    { home: "Shanghai Shenhua", away: "Chongqing Tonglianglong", home_score: 2, away_score: 2 },
    { home: "Chengdu Rongcheng", away: "Henan", home_score: 3, away_score: 0 },
    { home: "Qingdao Youth Island", away: "Wuhan Three Towns", home_score: 1, away_score: 1 },
    { home: "Shenzhen Peng City", away: "Shandong Taishan", home_score: 1, away_score: 2 },
    { home: "Shenyang Urban", away: "Yunnan Yukun", home_score: 1, away_score: 2 },
    { home: "Zhejiang", away: "Tianjin Jinmen Tiger", home_score: 1, away_score: 1 },
    { home: "Beijing Guoan", away: "Shanghai Port", home_score: 2, away_score: 2 },
    { home: "Qingdao Hainiu", away: "Dalian Yingbo", home_score: 3, away_score: 1 },
    
    // Matchday 12
    { home: "Henan", away: "Shenzhen Peng City", home_score: 1, away_score: 0 },
    { home: "Tianjin Jinmen Tiger", away: "Chengdu Rongcheng", home_score: 1, away_score: 2 },
    { home: "Shanghai Port", away: "Zhejiang", home_score: 2, away_score: 2 },
    { home: "Dalian Yingbo", away: "Qingdao Youth Island", home_score: 2, away_score: 3 },
    { home: "Beijing Guoan", away: "Qingdao Hainiu", home_score: 4, away_score: 2 },
    { home: "Wuhan Three Towns", away: "Shenyang Urban", home_score: 2, away_score: 2 },
    { home: "Shandong Taishan", away: "Chongqing Tonglianglong", home_score: 3, away_score: 1 },
    { home: "Yunnan Yukun", away: "Shanghai Shenhua", home_score: 1, away_score: 0 },
    
    // Matchday 13
    { home: "Tianjin Jinmen Tiger", away: "Henan", home_score: 1, away_score: 2 },
    { home: "Shenzhen Peng City", away: "Dalian Yingbo", home_score: 1, away_score: 1 },
    { home: "Qingdao Youth Island", away: "Beijing Guoan", home_score: 1, away_score: 1 },
    { home: "Chengdu Rongcheng", away: "Shanghai Port", home_score: 0, away_score: 1 },
    { home: "Shenyang Urban", away: "Qingdao Hainiu", home_score: 2, away_score: 1 },
    { home: "Shanghai Shenhua", away: "Wuhan Three Towns", home_score: 2, away_score: 2 },
    { home: "Chongqing Tonglianglong", away: "Yunnan Yukun", home_score: 0, away_score: 0 },
    { home: "Zhejiang", away: "Shandong Taishan", home_score: 4, away_score: 1 },
    
    // Matchday 14
    { home: "Shanghai Port", away: "Tianjin Jinmen Tiger", home_score: 1, away_score: 1 },
    { home: "Beijing Guoan", away: "Henan", home_score: 1, away_score: 2 },
    { home: "Dalian Yingbo", away: "Chengdu Rongcheng", home_score: 2, away_score: 0 },
    { home: "Qingdao Hainiu", away: "Chongqing Tonglianglong", home_score: 0, away_score: 1 },
    { home: "Yunnan Yukun", away: "Qingdao Youth Island", home_score: 2, away_score: 3 },
    { home: "Shandong Taishan", away: "Wuhan Three Towns", home_score: 3, away_score: 3 },
    { home: "Zhejiang", away: "Shenyang Urban", home_score: 0, away_score: 5 },
    { home: "Shanghai Shenhua", away: "Shenzhen Peng City", home_score: 1, away_score: 2 },
    
    // Matchday 15
    { home: "Shenyang Urban", away: "Shanghai Port", home_score: 3, away_score: 2 },
    { home: "Qingdao Youth Island", away: "Shanghai Shenhua", home_score: 2, away_score: 2 },
    { home: "Henan", away: "Zhejiang", home_score: 0, away_score: 2 },
    { home: "Chengdu Rongcheng", away: "Shandong Taishan", home_score: 1, away_score: 0 },
    { home: "Chongqing Tonglianglong", away: "Beijing Guoan", home_score: 2, away_score: 3 },
    { home: "Shenzhen Peng City", away: "Qingdao Hainiu", home_score: 3, away_score: 2 },
    
    // Matchday 16
    { home: "Tianjin Jinmen Tiger", away: "Dalian Yingbo", home_score: 1, away_score: 0 },
    { home: "Wuhan Three Towns", away: "Yunnan Yukun", home_score: 1, away_score: 1 }
],
	"NBA": [
    { home: "LA Lakers", away: "Boston Celtics", home_score: 112, away_score: 108 },
    { home: "Golden State Warriors", away: "Denver Nuggets", home_score: 115, away_score: 120 },
    // home_score and away_score represent POINTS, not goals
]
};

console.log("âœ… Complete matches data loaded successfully!");
console.log(`ðŸ“Š Loaded ${Object.keys(matchesData).length} leagues with match results`);